// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// APIToken maps the api_token table.
type APIToken struct {
	Beta       *string    `gorm:"column:beta" json:"beta"`
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	DialogID   *string    `gorm:"column:dialog_id" json:"dialog_id"`
	Source     *string    `gorm:"column:source" json:"source"`
	TenantID   string     `gorm:"column:tenant_id;primaryKey;autoIncrement:false;not null" json:"tenant_id"`
	Token      string     `gorm:"column:token;primaryKey;autoIncrement:false;not null" json:"token"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (APIToken) TableName() string { return "api_token" }
