// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// API4Conversation maps the api_4_conversation table.
type API4Conversation struct {
	CreateDate   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime   *int64     `gorm:"column:create_time" json:"create_time"`
	DialogID     string     `gorm:"column:dialog_id;not null" json:"dialog_id"`
	Dsl          *string    `gorm:"column:dsl" json:"dsl"`
	Duration     float64    `gorm:"column:duration;not null" json:"duration"`
	Errors       *string    `gorm:"column:errors" json:"errors"`
	ExpUserID    *string    `gorm:"column:exp_user_id" json:"exp_user_id"`
	ID           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Message      *string    `gorm:"column:message" json:"message"`
	Name         *string    `gorm:"column:name" json:"name"`
	Reference    *string    `gorm:"column:reference" json:"reference"`
	Round        int32      `gorm:"column:round;not null" json:"round"`
	Source       *string    `gorm:"column:source" json:"source"`
	ThumbUp      int32      `gorm:"column:thumb_up;not null" json:"thumb_up"`
	Tokens       int32      `gorm:"column:tokens;not null" json:"tokens"`
	UpdateDate   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime   *int64     `gorm:"column:update_time" json:"update_time"`
	UserID       string     `gorm:"column:user_id;not null" json:"user_id"`
	VersionTitle *string    `gorm:"column:version_title" json:"version_title"`
}

// TableName returns the exact table name.
func (API4Conversation) TableName() string { return "api_4_conversation" }
