// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// CanvasTemplate maps the canvas_template table.
type CanvasTemplate struct {
	Avatar         *string    `gorm:"column:avatar" json:"avatar"`
	CanvasCategory string     `gorm:"column:canvas_category;not null" json:"canvas_category"`
	CanvasType     *string    `gorm:"column:canvas_type" json:"canvas_type"`
	CanvasTypes    *string    `gorm:"column:canvas_types" json:"canvas_types"`
	CreateDate     *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime     *int64     `gorm:"column:create_time" json:"create_time"`
	Description    *string    `gorm:"column:description" json:"description"`
	Dsl            *string    `gorm:"column:dsl" json:"dsl"`
	ID             string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Title          *string    `gorm:"column:title" json:"title"`
	UpdateDate     *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime     *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (CanvasTemplate) TableName() string { return "canvas_template" }
