// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// ChatChannel maps the chat_channel table.
type ChatChannel struct {
	Channel    string     `gorm:"column:channel;not null" json:"channel"`
	ChatID     *string    `gorm:"column:chat_id" json:"chat_id"`
	Config     string     `gorm:"column:config;not null" json:"config"`
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Name       string     `gorm:"column:name;not null" json:"name"`
	Status     int32      `gorm:"column:status;not null" json:"status"`
	TenantID   string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (ChatChannel) TableName() string { return "chat_channel" }
