// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// CompilationTemplate maps the compilation_template table.
type CompilationTemplate struct {
	Config      string     `gorm:"column:config;not null" json:"config"`
	CreateDate  *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime  *int64     `gorm:"column:create_time" json:"create_time"`
	Description *string    `gorm:"column:description" json:"description"`
	GroupID     *string    `gorm:"column:group_id" json:"group_id"`
	ID          string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	IsBuiltin   bool       `gorm:"column:is_builtin;not null" json:"is_builtin"`
	Kind        string     `gorm:"column:kind;not null" json:"kind"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	Status      *string    `gorm:"column:status" json:"status"`
	TenantID    *string    `gorm:"column:tenant_id" json:"tenant_id"`
	UpdateDate  *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime  *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (CompilationTemplate) TableName() string { return "compilation_template" }
