// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Connector maps the connector table.
type Connector struct {
	Config        string     `gorm:"column:config;not null" json:"config"`
	CreateDate    *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime    *int64     `gorm:"column:create_time" json:"create_time"`
	ID            string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	IndexingStart *time.Time `gorm:"column:indexing_start" json:"indexing_start"`
	InputType     string     `gorm:"column:input_type;not null" json:"input_type"`
	Name          string     `gorm:"column:name;not null" json:"name"`
	PruneFreq     int32      `gorm:"column:prune_freq;not null" json:"prune_freq"`
	RefreshFreq   int32      `gorm:"column:refresh_freq;not null" json:"refresh_freq"`
	Source        string     `gorm:"column:source;not null" json:"source"`
	Status        *string    `gorm:"column:status" json:"status"`
	TenantID      string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	TimeoutSecs   int32      `gorm:"column:timeout_secs;not null" json:"timeout_secs"`
	UpdateDate    *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime    *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Connector) TableName() string { return "connector" }
