// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Connector2KB maps the connector2kb table.
type Connector2KB struct {
	AutoParse   string     `gorm:"column:auto_parse;not null" json:"auto_parse"`
	ConnectorID string     `gorm:"column:connector_id;not null" json:"connector_id"`
	CreateDate  *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime  *int64     `gorm:"column:create_time" json:"create_time"`
	ID          string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	KBID        string     `gorm:"column:kb_id;not null" json:"kb_id"`
	UpdateDate  *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime  *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Connector2KB) TableName() string { return "connector2kb" }
