// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Conversation maps the conversation table.
type Conversation struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	DialogID   string     `gorm:"column:dialog_id;not null" json:"dialog_id"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Message    *string    `gorm:"column:message" json:"message"`
	Name       *string    `gorm:"column:name" json:"name"`
	Reference  *string    `gorm:"column:reference" json:"reference"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	UserID     *string    `gorm:"column:user_id" json:"user_id"`
}

// TableName returns the exact table name.
func (Conversation) TableName() string { return "conversation" }
