// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Dialog maps the dialog table.
type Dialog struct {
	CreateDate             *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime             *int64     `gorm:"column:create_time" json:"create_time"`
	Description            *string    `gorm:"column:description" json:"description"`
	DoRefer                string     `gorm:"column:do_refer;not null" json:"do_refer"`
	Icon                   *string    `gorm:"column:icon" json:"icon"`
	ID                     string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	KBIds                  string     `gorm:"column:kb_ids;not null" json:"kb_ids"`
	Language               *string    `gorm:"column:language" json:"language"`
	LLMID                  string     `gorm:"column:llm_id;not null" json:"llm_id"`
	LLMSetting             string     `gorm:"column:llm_setting;not null" json:"llm_setting"`
	MetaDataFilter         *string    `gorm:"column:meta_data_filter" json:"meta_data_filter"`
	Name                   *string    `gorm:"column:name" json:"name"`
	PromptConfig           string     `gorm:"column:prompt_config;not null" json:"prompt_config"`
	PromptType             string     `gorm:"column:prompt_type;not null" json:"prompt_type"`
	RerankID               string     `gorm:"column:rerank_id;not null" json:"rerank_id"`
	SimilarityThreshold    float64    `gorm:"column:similarity_threshold;not null" json:"similarity_threshold"`
	Status                 *string    `gorm:"column:status" json:"status"`
	TenantID               string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	TenantLLMID            *string    `gorm:"column:tenant_llm_id" json:"tenant_llm_id"`
	TenantRerankID         *string    `gorm:"column:tenant_rerank_id" json:"tenant_rerank_id"`
	TopK                   int32      `gorm:"column:top_k;not null" json:"top_k"`
	TopN                   int32      `gorm:"column:top_n;not null" json:"top_n"`
	UpdateDate             *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime             *int64     `gorm:"column:update_time" json:"update_time"`
	VectorSimilarityWeight float64    `gorm:"column:vector_similarity_weight;not null" json:"vector_similarity_weight"`
}

// TableName returns the exact table name.
func (Dialog) TableName() string { return "dialog" }
