// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Document maps the document table.
type Document struct {
	ChunkNum        int32      `gorm:"column:chunk_num;not null" json:"chunk_num"`
	ContentHash     *string    `gorm:"column:content_hash" json:"content_hash"`
	CreateDate      *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime      *int64     `gorm:"column:create_time" json:"create_time"`
	CreatedBy       string     `gorm:"column:created_by;not null" json:"created_by"`
	ID              string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	KBID            string     `gorm:"column:kb_id;not null" json:"kb_id"`
	Location        *string    `gorm:"column:location" json:"location"`
	Name            *string    `gorm:"column:name" json:"name"`
	ParserConfig    string     `gorm:"column:parser_config;not null" json:"parser_config"`
	ParserID        string     `gorm:"column:parser_id;not null" json:"parser_id"`
	PipelineID      *string    `gorm:"column:pipeline_id" json:"pipeline_id"`
	ProcessBeginAt  *time.Time `gorm:"column:process_begin_at" json:"process_begin_at"`
	ProcessDuration float64    `gorm:"column:process_duration;not null" json:"process_duration"`
	Progress        float64    `gorm:"column:progress;not null" json:"progress"`
	ProgressMsg     *string    `gorm:"column:progress_msg" json:"progress_msg"`
	Run             *string    `gorm:"column:run" json:"run"`
	Size            int64      `gorm:"column:size;not null" json:"size"`
	SourceType      string     `gorm:"column:source_type;not null" json:"source_type"`
	Status          *string    `gorm:"column:status" json:"status"`
	Suffix          string     `gorm:"column:suffix;not null" json:"suffix"`
	Thumbnail       *string    `gorm:"column:thumbnail" json:"thumbnail"`
	TokenNum        int32      `gorm:"column:token_num;not null" json:"token_num"`
	Type            string     `gorm:"column:type;not null" json:"type"`
	UpdateDate      *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime      *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Document) TableName() string { return "document" }
