// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// File maps the file table.
type File struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	CreatedBy  string     `gorm:"column:created_by;not null" json:"created_by"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Location   *string    `gorm:"column:location" json:"location"`
	Name       string     `gorm:"column:name;not null" json:"name"`
	ParentID   string     `gorm:"column:parent_id;not null" json:"parent_id"`
	Size       int64      `gorm:"column:size;not null" json:"size"`
	SourceType string     `gorm:"column:source_type;not null" json:"source_type"`
	TenantID   string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Type       string     `gorm:"column:type;not null" json:"type"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (File) TableName() string { return "file" }
