// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// FileCommit maps the file_commit table.
type FileCommit struct {
	AuthorID   string     `gorm:"column:author_id;not null" json:"author_id"`
	Comments   *string    `gorm:"column:comments" json:"comments"`
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	FileCount  int32      `gorm:"column:file_count;not null" json:"file_count"`
	FolderID   string     `gorm:"column:folder_id;not null" json:"folder_id"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Message    string     `gorm:"column:message;not null" json:"message"`
	ParentID   *string    `gorm:"column:parent_id" json:"parent_id"`
	Title      *string    `gorm:"column:title" json:"title"`
	TreeState  *string    `gorm:"column:tree_state" json:"tree_state"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (FileCommit) TableName() string { return "file_commit" }
