// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// File2Document maps the file2document table.
type File2Document struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	DocumentID *string    `gorm:"column:document_id" json:"document_id"`
	FileID     *string    `gorm:"column:file_id" json:"file_id"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (File2Document) TableName() string { return "file2document" }
