// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// FileCommitItem maps the file_commit_item table.
type FileCommitItem struct {
	CommitID             string     `gorm:"column:commit_id;not null" json:"commit_id"`
	ContentAfterLocation *string    `gorm:"column:content_after_location" json:"content_after_location"`
	ContentAfterStorage  *string    `gorm:"column:content_after_storage" json:"content_after_storage"`
	CreateDate           *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime           *int64     `gorm:"column:create_time" json:"create_time"`
	Diff                 *string    `gorm:"column:diff" json:"diff"`
	FileID               string     `gorm:"column:file_id;not null" json:"file_id"`
	ID                   string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	NewHash              *string    `gorm:"column:new_hash" json:"new_hash"`
	NewLocation          *string    `gorm:"column:new_location" json:"new_location"`
	NewName              *string    `gorm:"column:new_name" json:"new_name"`
	OldHash              *string    `gorm:"column:old_hash" json:"old_hash"`
	OldLocation          *string    `gorm:"column:old_location" json:"old_location"`
	OldName              *string    `gorm:"column:old_name" json:"old_name"`
	Operation            string     `gorm:"column:operation;not null" json:"operation"`
	PageTypeKwd          *string    `gorm:"column:page_type_kwd" json:"page_type_kwd"`
	SlugKwd              *string    `gorm:"column:slug_kwd" json:"slug_kwd"`
	UpdateDate           *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime           *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (FileCommitItem) TableName() string { return "file_commit_item" }
