// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// InvitationCode maps the invitation_code table.
type InvitationCode struct {
	Code       string     `gorm:"column:code;not null" json:"code"`
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Status     *string    `gorm:"column:status" json:"status"`
	TenantID   *string    `gorm:"column:tenant_id" json:"tenant_id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	UserID     *string    `gorm:"column:user_id" json:"user_id"`
	VisitTime  *time.Time `gorm:"column:visit_time" json:"visit_time"`
}

// TableName returns the exact table name.
func (InvitationCode) TableName() string { return "invitation_code" }
