// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Knowledgebase maps the knowledgebase table.
type Knowledgebase struct {
	Avatar                       *string    `gorm:"column:avatar" json:"avatar"`
	ChunkNum                     int32      `gorm:"column:chunk_num;not null" json:"chunk_num"`
	CreateDate                   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime                   *int64     `gorm:"column:create_time" json:"create_time"`
	CreatedBy                    string     `gorm:"column:created_by;not null" json:"created_by"`
	Description                  *string    `gorm:"column:description" json:"description"`
	DocNum                       int32      `gorm:"column:doc_num;not null" json:"doc_num"`
	EmbdID                       string     `gorm:"column:embd_id;not null" json:"embd_id"`
	GraphragTaskFinishAt         *time.Time `gorm:"column:graphrag_task_finish_at" json:"graphrag_task_finish_at"`
	GraphragTaskID               *string    `gorm:"column:graphrag_task_id" json:"graphrag_task_id"`
	ID                           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Language                     *string    `gorm:"column:language" json:"language"`
	MindmapTaskFinishAt          *time.Time `gorm:"column:mindmap_task_finish_at" json:"mindmap_task_finish_at"`
	MindmapTaskID                *string    `gorm:"column:mindmap_task_id" json:"mindmap_task_id"`
	Name                         string     `gorm:"column:name;not null" json:"name"`
	Pagerank                     int32      `gorm:"column:pagerank;not null" json:"pagerank"`
	ParserConfig                 string     `gorm:"column:parser_config;not null" json:"parser_config"`
	ParserID                     string     `gorm:"column:parser_id;not null" json:"parser_id"`
	Permission                   string     `gorm:"column:permission;not null" json:"permission"`
	PipelineID                   *string    `gorm:"column:pipeline_id" json:"pipeline_id"`
	RaptorTaskFinishAt           *time.Time `gorm:"column:raptor_task_finish_at" json:"raptor_task_finish_at"`
	RaptorTaskID                 *string    `gorm:"column:raptor_task_id" json:"raptor_task_id"`
	SessionEssenceTaskFinishAt   *time.Time `gorm:"column:session_essence_task_finish_at" json:"session_essence_task_finish_at"`
	SessionEssenceTaskID         *string    `gorm:"column:session_essence_task_id" json:"session_essence_task_id"`
	SessionGraphTaskFinishAt     *time.Time `gorm:"column:session_graph_task_finish_at" json:"session_graph_task_finish_at"`
	SessionGraphTaskID           *string    `gorm:"column:session_graph_task_id" json:"session_graph_task_id"`
	SimilarityThreshold          float64    `gorm:"column:similarity_threshold;not null" json:"similarity_threshold"`
	SkillTaskFinishAt            *time.Time `gorm:"column:skill_task_finish_at" json:"skill_task_finish_at"`
	SkillTaskID                  *string    `gorm:"column:skill_task_id" json:"skill_task_id"`
	Status                       *string    `gorm:"column:status" json:"status"`
	StructureGraphTaskFinishAt   *time.Time `gorm:"column:structure_graph_task_finish_at" json:"structure_graph_task_finish_at"`
	StructureGraphTaskID         *string    `gorm:"column:structure_graph_task_id" json:"structure_graph_task_id"`
	StructureMindmapTaskFinishAt *time.Time `gorm:"column:structure_mindmap_task_finish_at" json:"structure_mindmap_task_finish_at"`
	StructureMindmapTaskID       *string    `gorm:"column:structure_mindmap_task_id" json:"structure_mindmap_task_id"`
	StructureTaskFinishAt        *time.Time `gorm:"column:structure_task_finish_at" json:"structure_task_finish_at"`
	StructureTaskID              *string    `gorm:"column:structure_task_id" json:"structure_task_id"`
	TenantEmbdID                 *string    `gorm:"column:tenant_embd_id" json:"tenant_embd_id"`
	TenantID                     string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	TimelineTaskFinishAt         *time.Time `gorm:"column:timeline_task_finish_at" json:"timeline_task_finish_at"`
	TimelineTaskID               *string    `gorm:"column:timeline_task_id" json:"timeline_task_id"`
	TokenNum                     int32      `gorm:"column:token_num;not null" json:"token_num"`
	UpdateDate                   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime                   *int64     `gorm:"column:update_time" json:"update_time"`
	VectorSimilarityWeight       float64    `gorm:"column:vector_similarity_weight;not null" json:"vector_similarity_weight"`
	WikiTaskFinishAt             *time.Time `gorm:"column:wiki_task_finish_at" json:"wiki_task_finish_at"`
	WikiTaskID                   *string    `gorm:"column:wiki_task_id" json:"wiki_task_id"`
}

// TableName returns the exact table name.
func (Knowledgebase) TableName() string { return "knowledgebase" }
