// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// LLM maps the llm table.
type LLM struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	Fid        string     `gorm:"column:fid;primaryKey;autoIncrement:false;not null" json:"fid"`
	IsTools    bool       `gorm:"column:is_tools;not null" json:"is_tools"`
	LLMName    string     `gorm:"column:llm_name;primaryKey;autoIncrement:false;not null" json:"llm_name"`
	MaxTokens  int32      `gorm:"column:max_tokens;not null" json:"max_tokens"`
	ModelType  string     `gorm:"column:model_type;not null" json:"model_type"`
	Status     *string    `gorm:"column:status" json:"status"`
	Tags       string     `gorm:"column:tags;not null" json:"tags"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (LLM) TableName() string { return "llm" }
