// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// LLMFactories maps the llm_factories table.
type LLMFactories struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	Logo       *string    `gorm:"column:logo" json:"logo"`
	Name       string     `gorm:"column:name;primaryKey;autoIncrement:false;not null" json:"name"`
	Rank       int32      `gorm:"column:rank;not null" json:"rank"`
	Status     *string    `gorm:"column:status" json:"status"`
	Tags       string     `gorm:"column:tags;not null" json:"tags"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (LLMFactories) TableName() string { return "llm_factories" }
