// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// MCPServer maps the mcp_server table.
type MCPServer struct {
	CreateDate  *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime  *int64     `gorm:"column:create_time" json:"create_time"`
	Description *string    `gorm:"column:description" json:"description"`
	Headers     *string    `gorm:"column:headers" json:"headers"`
	ID          string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	ServerType  string     `gorm:"column:server_type;not null" json:"server_type"`
	TenantID    string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate  *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime  *int64     `gorm:"column:update_time" json:"update_time"`
	URL         string     `gorm:"column:url;not null" json:"url"`
	Variables   *string    `gorm:"column:variables" json:"variables"`
}

// TableName returns the exact table name.
func (MCPServer) TableName() string { return "mcp_server" }
