// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Memory maps the memory table.
type Memory struct {
	Avatar           *string    `gorm:"column:avatar" json:"avatar"`
	CreateDate       *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime       *int64     `gorm:"column:create_time" json:"create_time"`
	Description      *string    `gorm:"column:description" json:"description"`
	EmbdID           string     `gorm:"column:embd_id;not null" json:"embd_id"`
	ForgettingPolicy string     `gorm:"column:forgetting_policy;not null" json:"forgetting_policy"`
	ID               string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	LLMID            string     `gorm:"column:llm_id;not null" json:"llm_id"`
	MemorySize       int32      `gorm:"column:memory_size;not null" json:"memory_size"`
	MemoryType       int32      `gorm:"column:memory_type;not null" json:"memory_type"`
	Name             string     `gorm:"column:name;not null" json:"name"`
	Permissions      string     `gorm:"column:permissions;not null" json:"permissions"`
	StorageType      string     `gorm:"column:storage_type;not null" json:"storage_type"`
	SystemPrompt     *string    `gorm:"column:system_prompt" json:"system_prompt"`
	Temperature      float64    `gorm:"column:temperature;not null" json:"temperature"`
	TenantEmbdID     *string    `gorm:"column:tenant_embd_id" json:"tenant_embd_id"`
	TenantID         string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	TenantLLMID      *string    `gorm:"column:tenant_llm_id" json:"tenant_llm_id"`
	UpdateDate       *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime       *int64     `gorm:"column:update_time" json:"update_time"`
	UserPrompt       *string    `gorm:"column:user_prompt" json:"user_prompt"`
}

// TableName returns the exact table name.
func (Memory) TableName() string { return "memory" }
