// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// PipelineOperationLog maps the pipeline_operation_log table.
type PipelineOperationLog struct {
	Avatar          *string    `gorm:"column:avatar" json:"avatar"`
	CreateDate      *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime      *int64     `gorm:"column:create_time" json:"create_time"`
	DocumentID      string     `gorm:"column:document_id;not null" json:"document_id"`
	DocumentName    string     `gorm:"column:document_name;not null" json:"document_name"`
	DocumentSuffix  string     `gorm:"column:document_suffix;not null" json:"document_suffix"`
	DocumentType    string     `gorm:"column:document_type;not null" json:"document_type"`
	Dsl             *string    `gorm:"column:dsl" json:"dsl"`
	ID              string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	KBID            string     `gorm:"column:kb_id;not null" json:"kb_id"`
	OperationStatus string     `gorm:"column:operation_status;not null" json:"operation_status"`
	ParserID        string     `gorm:"column:parser_id;not null" json:"parser_id"`
	PipelineID      *string    `gorm:"column:pipeline_id" json:"pipeline_id"`
	PipelineTitle   *string    `gorm:"column:pipeline_title" json:"pipeline_title"`
	ProcessBeginAt  *time.Time `gorm:"column:process_begin_at" json:"process_begin_at"`
	ProcessDuration float64    `gorm:"column:process_duration;not null" json:"process_duration"`
	Progress        float64    `gorm:"column:progress;not null" json:"progress"`
	ProgressMsg     *string    `gorm:"column:progress_msg" json:"progress_msg"`
	SourceFrom      string     `gorm:"column:source_from;not null" json:"source_from"`
	Status          *string    `gorm:"column:status" json:"status"`
	TaskType        string     `gorm:"column:task_type;not null" json:"task_type"`
	TenantID        string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate      *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime      *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (PipelineOperationLog) TableName() string { return "pipeline_operation_log" }
