// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

// Package entity holds the GORM mappings of the tables the Python engine owns.
// They are read-only mappings: Go never creates or alters a table (D-10).
package entity

// All lists one zero value of every entity, for schema verification.
func All() []any {
	return []any{
		API4Conversation{},
		APIToken{},
		CanvasTemplate{},
		ChatChannel{},
		CompilationTemplate{},
		CompilationTemplateGroup{},
		Connector{},
		Connector2KB{},
		Conversation{},
		Dialog{},
		Document{},
		File{},
		File2Document{},
		FileCommit{},
		FileCommitItem{},
		InvitationCode{},
		Knowledgebase{},
		LLM{},
		LLMFactories{},
		MCPServer{},
		Memory{},
		PipelineOperationLog{},
		Search{},
		SyncLogs{},
		SystemSettings{},
		Task{},
		Tenant{},
		TenantLangfuse{},
		TenantLLM{},
		TenantModel{},
		TenantModelGroup{},
		TenantModelGroupMapping{},
		TenantModelInstance{},
		TenantModelProvider{},
		User{},
		UserCanvas{},
		UserCanvasVersion{},
		UserTenant{},
	}
}
