// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Search maps the search table.
type Search struct {
	Avatar       *string    `gorm:"column:avatar" json:"avatar"`
	CreateDate   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime   *int64     `gorm:"column:create_time" json:"create_time"`
	CreatedBy    string     `gorm:"column:created_by;not null" json:"created_by"`
	Description  *string    `gorm:"column:description" json:"description"`
	ID           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Name         string     `gorm:"column:name;not null" json:"name"`
	SearchConfig string     `gorm:"column:search_config;not null" json:"search_config"`
	Status       *string    `gorm:"column:status" json:"status"`
	TenantID     string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime   *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Search) TableName() string { return "search" }
