// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// SyncLogs maps the sync_logs table.
type SyncLogs struct {
	ConnectorID          string     `gorm:"column:connector_id;not null" json:"connector_id"`
	CreateDate           *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime           *int64     `gorm:"column:create_time" json:"create_time"`
	DocsRemovedFromIndex int32      `gorm:"column:docs_removed_from_index;not null" json:"docs_removed_from_index"`
	ErrorCount           int32      `gorm:"column:error_count;not null" json:"error_count"`
	ErrorMsg             string     `gorm:"column:error_msg;not null" json:"error_msg"`
	FromBeginning        *string    `gorm:"column:from_beginning" json:"from_beginning"`
	FullExceptionTrace   *string    `gorm:"column:full_exception_trace" json:"full_exception_trace"`
	ID                   string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	KBID                 string     `gorm:"column:kb_id;not null" json:"kb_id"`
	NewDocsIndexed       int32      `gorm:"column:new_docs_indexed;not null" json:"new_docs_indexed"`
	PollRangeEnd         *string    `gorm:"column:poll_range_end" json:"poll_range_end"`
	PollRangeStart       *string    `gorm:"column:poll_range_start" json:"poll_range_start"`
	Status               string     `gorm:"column:status;not null" json:"status"`
	TaskType             string     `gorm:"column:task_type;not null" json:"task_type"`
	TimeStarted          *time.Time `gorm:"column:time_started" json:"time_started"`
	TotalDocsIndexed     int32      `gorm:"column:total_docs_indexed;not null" json:"total_docs_indexed"`
	UpdateDate           *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime           *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (SyncLogs) TableName() string { return "sync_logs" }
