// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// SystemSettings maps the system_settings table.
type SystemSettings struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	DataType   string     `gorm:"column:data_type;not null" json:"data_type"`
	Name       string     `gorm:"column:name;primaryKey;autoIncrement:false;not null" json:"name"`
	Source     string     `gorm:"column:source;not null" json:"source"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	Value      string     `gorm:"column:value;not null" json:"value"`
}

// TableName returns the exact table name.
func (SystemSettings) TableName() string { return "system_settings" }
