// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Task maps the task table.
type Task struct {
	BeginAt         *time.Time `gorm:"column:begin_at" json:"begin_at"`
	ChunkIds        *string    `gorm:"column:chunk_ids" json:"chunk_ids"`
	CreateDate      *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime      *int64     `gorm:"column:create_time" json:"create_time"`
	Digest          *string    `gorm:"column:digest" json:"digest"`
	DocID           string     `gorm:"column:doc_id;not null" json:"doc_id"`
	FromPage        int32      `gorm:"column:from_page;not null" json:"from_page"`
	ID              string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Priority        int32      `gorm:"column:priority;not null" json:"priority"`
	ProcessDuration float64    `gorm:"column:process_duration;not null" json:"process_duration"`
	Progress        float64    `gorm:"column:progress;not null" json:"progress"`
	ProgressMsg     *string    `gorm:"column:progress_msg" json:"progress_msg"`
	RetryCount      int32      `gorm:"column:retry_count;not null" json:"retry_count"`
	TaskType        string     `gorm:"column:task_type;not null" json:"task_type"`
	ToPage          int32      `gorm:"column:to_page;not null" json:"to_page"`
	UpdateDate      *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime      *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Task) TableName() string { return "task" }
