// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantLLM maps the tenant_llm table.
type TenantLLM struct {
	APIBase    *string    `gorm:"column:api_base" json:"api_base"`
	APIKey     *string    `gorm:"column:api_key" json:"api_key"`
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	ID         int32      `gorm:"column:id;primaryKey;not null" json:"id"`
	LLMFactory string     `gorm:"column:llm_factory;not null" json:"llm_factory"`
	LLMName    *string    `gorm:"column:llm_name" json:"llm_name"`
	MaxTokens  int32      `gorm:"column:max_tokens;not null" json:"max_tokens"`
	ModelType  *string    `gorm:"column:model_type" json:"model_type"`
	Status     string     `gorm:"column:status;not null" json:"status"`
	TenantID   string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	UsedTokens int32      `gorm:"column:used_tokens;not null" json:"used_tokens"`
}

// TableName returns the exact table name.
func (TenantLLM) TableName() string { return "tenant_llm" }
