// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantLangfuse maps the tenant_langfuse table.
type TenantLangfuse struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	Host       string     `gorm:"column:host;not null" json:"host"`
	PublicKey  string     `gorm:"column:public_key;not null" json:"public_key"`
	SecretKey  string     `gorm:"column:secret_key;not null" json:"secret_key"`
	TenantID   string     `gorm:"column:tenant_id;primaryKey;autoIncrement:false;not null" json:"tenant_id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (TenantLangfuse) TableName() string { return "tenant_langfuse" }
