// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantModelInstance maps the tenant_model_instance table.
type TenantModelInstance struct {
	APIKey       string     `gorm:"column:api_key;not null" json:"api_key"`
	CreateDate   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime   *int64     `gorm:"column:create_time" json:"create_time"`
	Extra        string     `gorm:"column:extra;not null" json:"extra"`
	ID           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	InstanceName string     `gorm:"column:instance_name;not null" json:"instance_name"`
	ProviderID   string     `gorm:"column:provider_id;not null" json:"provider_id"`
	Status       string     `gorm:"column:status;not null" json:"status"`
	UpdateDate   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime   *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (TenantModelInstance) TableName() string { return "tenant_model_instance" }
