// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantModelProvider maps the tenant_model_provider table.
type TenantModelProvider struct {
	CreateDate   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime   *int64     `gorm:"column:create_time" json:"create_time"`
	ID           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	ProviderName string     `gorm:"column:provider_name;not null" json:"provider_name"`
	TenantID     string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime   *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (TenantModelProvider) TableName() string { return "tenant_model_provider" }
