// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantModelGroupMapping maps the tenant_model_group_mapping table.
type TenantModelGroupMapping struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	GroupID    string     `gorm:"column:group_id;primaryKey;autoIncrement:false;not null" json:"group_id"`
	InstanceID string     `gorm:"column:instance_id;primaryKey;autoIncrement:false;not null" json:"instance_id"`
	ModelID    string     `gorm:"column:model_id;primaryKey;autoIncrement:false;not null" json:"model_id"`
	ProviderID string     `gorm:"column:provider_id;primaryKey;autoIncrement:false;not null" json:"provider_id"`
	Status     string     `gorm:"column:status;not null" json:"status"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	Weight     int32      `gorm:"column:weight;not null" json:"weight"`
}

// TableName returns the exact table name.
func (TenantModelGroupMapping) TableName() string { return "tenant_model_group_mapping" }
