// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantModelGroup maps the tenant_model_group table.
type TenantModelGroup struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	GroupType  string     `gorm:"column:group_type;not null" json:"group_type"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	ModelName  *string    `gorm:"column:model_name" json:"model_name"`
	Strategy   string     `gorm:"column:strategy;not null" json:"strategy"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (TenantModelGroup) TableName() string { return "tenant_model_group" }
