// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// TenantModel maps the tenant_model table.
type TenantModel struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	Extra      string     `gorm:"column:extra;not null" json:"extra"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	InstanceID string     `gorm:"column:instance_id;not null" json:"instance_id"`
	ModelName  *string    `gorm:"column:model_name" json:"model_name"`
	ModelType  int32      `gorm:"column:model_type;not null" json:"model_type"`
	ProviderID string     `gorm:"column:provider_id;not null" json:"provider_id"`
	Status     string     `gorm:"column:status;not null" json:"status"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (TenantModel) TableName() string { return "tenant_model" }
