// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// Tenant maps the tenant table.
type Tenant struct {
	AsrID           string     `gorm:"column:asr_id;not null" json:"asr_id"`
	CreateDate      *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime      *int64     `gorm:"column:create_time" json:"create_time"`
	Credit          int32      `gorm:"column:credit;not null" json:"credit"`
	EmbdID          string     `gorm:"column:embd_id;not null" json:"embd_id"`
	ID              string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Img2txtID       string     `gorm:"column:img2txt_id;not null" json:"img2txt_id"`
	LLMID           string     `gorm:"column:llm_id;not null" json:"llm_id"`
	Name            *string    `gorm:"column:name" json:"name"`
	OcrID           *string    `gorm:"column:ocr_id" json:"ocr_id"`
	ParserIds       string     `gorm:"column:parser_ids;not null" json:"parser_ids"`
	PublicKey       *string    `gorm:"column:public_key" json:"public_key"`
	RerankID        string     `gorm:"column:rerank_id;not null" json:"rerank_id"`
	Status          *string    `gorm:"column:status" json:"status"`
	TenantAsrID     *string    `gorm:"column:tenant_asr_id" json:"tenant_asr_id"`
	TenantEmbdID    *string    `gorm:"column:tenant_embd_id" json:"tenant_embd_id"`
	TenantImg2txtID *string    `gorm:"column:tenant_img2txt_id" json:"tenant_img2txt_id"`
	TenantLLMID     *string    `gorm:"column:tenant_llm_id" json:"tenant_llm_id"`
	TenantOcrID     *string    `gorm:"column:tenant_ocr_id" json:"tenant_ocr_id"`
	TenantRerankID  *string    `gorm:"column:tenant_rerank_id" json:"tenant_rerank_id"`
	TenantTtsID     *string    `gorm:"column:tenant_tts_id" json:"tenant_tts_id"`
	TtsID           *string    `gorm:"column:tts_id" json:"tts_id"`
	UpdateDate      *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime      *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (Tenant) TableName() string { return "tenant" }
