// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// UserCanvasVersion maps the user_canvas_version table.
type UserCanvasVersion struct {
	CreateDate   *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime   *int64     `gorm:"column:create_time" json:"create_time"`
	Description  *string    `gorm:"column:description" json:"description"`
	Dsl          *string    `gorm:"column:dsl" json:"dsl"`
	ID           string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Release      bool       `gorm:"column:release;not null" json:"release"`
	Title        *string    `gorm:"column:title" json:"title"`
	UpdateDate   *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime   *int64     `gorm:"column:update_time" json:"update_time"`
	UserCanvasID string     `gorm:"column:user_canvas_id;not null" json:"user_canvas_id"`
}

// TableName returns the exact table name.
func (UserCanvasVersion) TableName() string { return "user_canvas_version" }
