// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// User maps the user table.
type User struct {
	AccessToken     *string    `gorm:"column:access_token" json:"access_token"`
	Avatar          *string    `gorm:"column:avatar" json:"avatar"`
	ColorSchema     *string    `gorm:"column:color_schema" json:"color_schema"`
	CreateDate      *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime      *int64     `gorm:"column:create_time" json:"create_time"`
	Email           string     `gorm:"column:email;not null" json:"email"`
	ID              string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	IsActive        string     `gorm:"column:is_active;not null" json:"is_active"`
	IsAnonymous     string     `gorm:"column:is_anonymous;not null" json:"is_anonymous"`
	IsAuthenticated string     `gorm:"column:is_authenticated;not null" json:"is_authenticated"`
	IsSuperuser     *bool      `gorm:"column:is_superuser" json:"is_superuser"`
	Language        *string    `gorm:"column:language" json:"language"`
	LastLoginTime   *time.Time `gorm:"column:last_login_time" json:"last_login_time"`
	LoginChannel    *string    `gorm:"column:login_channel" json:"login_channel"`
	Nickname        string     `gorm:"column:nickname;not null" json:"nickname"`
	Password        *string    `gorm:"column:password" json:"password"`
	Status          *string    `gorm:"column:status" json:"status"`
	Timezone        *string    `gorm:"column:timezone" json:"timezone"`
	UpdateDate      *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime      *int64     `gorm:"column:update_time" json:"update_time"`
}

// TableName returns the exact table name.
func (User) TableName() string { return "user" }
