// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// UserCanvas maps the user_canvas table.
type UserCanvas struct {
	Avatar         *string    `gorm:"column:avatar" json:"avatar"`
	CanvasCategory string     `gorm:"column:canvas_category;not null" json:"canvas_category"`
	CanvasType     *string    `gorm:"column:canvas_type" json:"canvas_type"`
	CreateDate     *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime     *int64     `gorm:"column:create_time" json:"create_time"`
	Description    *string    `gorm:"column:description" json:"description"`
	Dsl            *string    `gorm:"column:dsl" json:"dsl"`
	ID             string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	Permission     string     `gorm:"column:permission;not null" json:"permission"`
	Release        bool       `gorm:"column:release;not null" json:"release"`
	Tags           string     `gorm:"column:tags;not null" json:"tags"`
	Title          *string    `gorm:"column:title" json:"title"`
	UpdateDate     *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime     *int64     `gorm:"column:update_time" json:"update_time"`
	UserID         string     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName returns the exact table name.
func (UserCanvas) TableName() string { return "user_canvas" }
