// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.

package entity

import "time"

// UserTenant maps the user_tenant table.
type UserTenant struct {
	CreateDate *time.Time `gorm:"column:create_date" json:"create_date"`
	CreateTime *int64     `gorm:"column:create_time" json:"create_time"`
	ID         string     `gorm:"column:id;primaryKey;autoIncrement:false;not null" json:"id"`
	InvitedBy  string     `gorm:"column:invited_by;not null" json:"invited_by"`
	Role       string     `gorm:"column:role;not null" json:"role"`
	Status     *string    `gorm:"column:status" json:"status"`
	TenantID   string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	UpdateDate *time.Time `gorm:"column:update_date" json:"update_date"`
	UpdateTime *int64     `gorm:"column:update_time" json:"update_time"`
	UserID     string     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName returns the exact table name.
func (UserTenant) TableName() string { return "user_tenant" }
