"""Permission matrix, generated by scripts/gen_routes.py, do not edit. Source: conf/permissions.yaml."""
from __future__ import annotations

# (area, action) -> subjects allowed. Anything not listed is denied.
_ROWS: dict[tuple[str, str], tuple[str, ...]] = {
    ('agent_canvas', 'manage_flow'): ('owner', 'admin', 'normal', 'api_token'),
    ('agent_canvas', 'stream_completion'): ('owner', 'admin', 'normal', 'beta_token', 'api_token'),
    ('datasets', 'manage_dataset'): ('owner', 'admin', 'normal', 'api_token'),
    ('datasets', 'manage_document'): ('owner', 'admin', 'normal', 'api_token'),
    ('datasets', 'retrieval_test'): ('owner', 'admin', 'normal', 'beta_token', 'api_token'),
    ('enterprise_admin', 'view_health'): ('owner', 'admin'),
    ('mcp_server', 'tool_call'): ('owner', 'admin', 'normal', 'beta_token', 'api_token'),
    ('search_bots', 'ask'): ('owner', 'admin', 'normal', 'beta_token', 'api_token'),
    ('team_admin', 'manage_members'): ('owner',),
    ('tenant_settings', 'set_default_models'): ('owner', 'admin'),
    ('tenant_settings', 'update_llm_keys'): ('owner', 'admin'),
    ('tenant_settings', 'view_models'): ('owner', 'admin', 'normal', 'api_token'),
}


def rows() -> dict[tuple[str, str], tuple[str, ...]]:
    """A copy of the matrix (tests compare it with the Go table)."""
    return dict(_ROWS)


def allowed(subject: str, area: str, action: str) -> bool:
    """True only for a listed (area, action) whose allow list names subject. Unknown subjects (including the
    pending role `invite`), areas and actions are denied (D-26)."""
    return subject in _ROWS.get((area, action), ())
