"""Route policy resolver, generated by scripts/gen_routes.py, do not edit. Source: conf/routes.yaml."""
from __future__ import annotations

from typing import NamedTuple


class RoutePolicy(NamedTuple):
    """Resolved access policy. Unmatched paths resolve to auth jwt (default deny)."""

    auth: str
    roles: tuple[str, ...]
    scope: str
    owner: str
    preflight: bool


_EXACT: dict[str, tuple[str, str]] = {
    '/api/v1/auth/logout': ('go', 'jwt'),
    '/api/v1/language': ('go', 'none'),
    '/api/v1/mcp': ('go', 'beta'),
    '/api/v1/system/config': ('go', 'none'),
    '/api/v1/system/healthz': ('python', 'none'),
    '/api/v1/system/ping': ('go', 'none'),
    '/api/v1/system/status': ('python', 'jwt'),
    '/api/v1/system/tokens': ('go', 'jwt'),
    '/api/v1/system/version': ('go', 'jwt'),
    '/api/v1/users': ('go', 'none'),
    '/health': ('go', 'none'),
    '/system/healthz': ('python', 'none'),
    '/system/status': ('python', 'jwt'),
}

_PREFIX: tuple[tuple[str, str, str], ...] = (
    ('/api/v1/system/tokens/', 'go', 'jwt'),
    ('/api/v1/searchbots/', 'go', 'beta'),
    ('/api/v1/tenants/', 'go', 'jwt'),
    ('/api/v1/auth/', 'go', 'none'),
    ('/v1/tenant/', 'go', 'jwt'),
    ('/v1/user/', 'go', 'jwt'),
    ('/api/', 'python', 'api'),
    ('/v1/', 'python', 'api'),
)

_ROWS: tuple[tuple[str, tuple[str, ...], str, str, str, tuple[str, ...]], ...] = (
    ('POST', ('api', 'v1', 'auth', 'login'), 'go', 'none', 'none', ()),
    ('POST', ('api', 'v1', 'auth', 'logout'), 'go', 'jwt', 'none', ()),
    ('POST', ('api', 'v1', 'auth', 'password', 'forgot', 'otp'), 'go', 'none', 'none', ()),
    ('POST', ('api', 'v1', 'auth', 'password', 'forgot', 'otp', 'verify'), 'go', 'none', 'none', ()),
    ('POST', ('api', 'v1', 'auth', 'password', 'reset'), 'go', 'none', 'none', ()),
    ('GET', ('api', 'v1', 'language'), 'go', 'none', 'none', ()),
    ('GET', ('api', 'v1', 'openapi.json'), 'python', 'api', 'none', ()),
    ('POST', ('api', 'v1', 'searchbots', 'ask'), 'go', 'beta', 'none', ()),
    ('POST', ('api', 'v1', 'searchbots', 'retrieval_test'), 'go', 'beta', 'none', ()),
    ('GET', ('api', 'v1', 'system', 'config'), 'go', 'none', 'none', ()),
    ('GET', ('api', 'v1', 'system', 'healthz'), 'python', 'none', 'none', ()),
    ('GET', ('api', 'v1', 'system', 'ping'), 'go', 'none', 'none', ()),
    ('GET', ('api', 'v1', 'system', 'status'), 'python', 'jwt', 'none', ()),
    ('GET', ('api', 'v1', 'system', 'tokens'), 'go', 'jwt', 'tenant', ('owner',)),
    ('POST', ('api', 'v1', 'system', 'tokens'), 'go', 'jwt', 'tenant', ('owner',)),
    ('DELETE', ('api', 'v1', 'system', 'tokens', '{token}'), 'go', 'jwt', 'tenant', ('owner',)),
    ('GET', ('api', 'v1', 'system', 'version'), 'go', 'jwt', 'none', ()),
    ('PATCH', ('api', 'v1', 'tenants', '{tenant_id}'), 'go', 'jwt', 'tenant', ('invite',)),
    ('DELETE', ('api', 'v1', 'tenants', '{tenant_id}', 'users'), 'go', 'jwt', 'tenant', ('owner', 'self')),
    ('GET', ('api', 'v1', 'tenants', '{tenant_id}', 'users'), 'go', 'jwt', 'tenant', ('owner', 'admin', 'normal')),
    ('POST', ('api', 'v1', 'tenants', '{tenant_id}', 'users'), 'go', 'jwt', 'tenant', ('owner',)),
    ('PATCH', ('api', 'v1', 'tenants', '{tenant_id}', 'users', '{user_id}'), 'go', 'jwt', 'tenant', ('owner',)),
    ('POST', ('api', 'v1', 'users'), 'go', 'none', 'none', ()),
    ('GET', ('health',), 'go', 'none', 'none', ()),
    ('GET', ('system', 'healthz'), 'python', 'none', 'none', ()),
    ('GET', ('system', 'status'), 'python', 'jwt', 'none', ()),
    ('GET', ('v1', 'tenant', 'list'), 'go', 'jwt', 'none', ()),
    ('GET', ('v1', 'user', 'info'), 'go', 'jwt', 'none', ()),
    ('POST', ('v1', 'user', 'setting'), 'go', 'jwt', 'none', ()),
    ('POST', ('v1', 'user', 'setting', 'password'), 'go', 'jwt', 'none', ()),
    ('GET', ('v1', 'user', 'tenant_info'), 'go', 'jwt', 'none', ()),
)


def _row_matches(segments: tuple[str, ...], path: str) -> bool:
    parts = path.removeprefix("/").split("/")
    if len(parts) != len(segments):
        return False
    for seg, part in zip(segments, parts, strict=True):
        if seg.startswith("{") and seg.endswith("}"):
            if not part:
                return False
        elif seg != part:
            return False
    return True


def policy_for(method: str, path: str) -> RoutePolicy:
    """Registry row (method and path), then exact family, then longest prefix family, then default jwt (deny)."""
    preflight = method == "OPTIONS"
    if not preflight:
        for row_method, segments, owner, auth, scope, roles in _ROWS:
            if row_method == method and _row_matches(segments, path):
                return RoutePolicy(auth, roles, scope, owner, False)
    if path in _EXACT:
        owner, auth = _EXACT[path]
        return RoutePolicy(auth, (), "none", owner, preflight)
    for prefix, owner, auth in _PREFIX:
        if path.startswith(prefix):
            return RoutePolicy(auth, (), "none", owner, preflight)
    return RoutePolicy("jwt", (), "none", "", preflight)
