// Package conf embeds the Peewee schema export so the Go binary can verify the live database
// against it without reading files at runtime.
package conf

import _ "embed"

// SchemaJSON is conf/schema.json, generated by scripts/export_schema.py.
//
//go:embed schema.json
var SchemaJSON []byte
