"""Storage interface, key scheme and key validation (plan 03-07, STOR-01, STOR-11, SEC-06).

Every driver (MinIO, local) implements :class:`Storage`. Drivers are synchronous and blocking: callers run them in a bounded
executor. Object keys are always server-generated by :func:`new_object_key` as ``{tenant_id}/{uuid4 hex}``; a client file name
is never part of a key or a path. Error messages name the operation and bucket only, never a key, a path or a credential.
"""
from __future__ import annotations

import re
import uuid
from abc import ABC, abstractmethod
from collections.abc import Iterator
from typing import BinaryIO

TENANT_ID_RE = re.compile(r"[0-9a-f]{32}")
MAX_KEY_LENGTH = 255
DEFAULT_PRESIGN_SECONDS = 3600
DEFAULT_CHUNK_SIZE = 1 << 20


class StorageError(Exception):
    """A storage operation failed or was refused. The message never contains a key, path or credential."""


class StorageNotFound(StorageError):
    """The requested object does not exist."""


class StorageNotSupported(StorageError):
    """The driver does not implement the requested operation."""


def new_object_key(tenant_id: str) -> str:
    """Return a fresh ``{tenant_id}/{uuid4 hex}`` key. The tenant id must be 32 lowercase hex characters."""
    if not isinstance(tenant_id, str) or TENANT_ID_RE.fullmatch(tenant_id) is None:
        raise StorageError("invalid tenant id for object key")
    return f"{tenant_id}/{uuid.uuid4().hex}"


def validate_key(key: str) -> None:
    """Reject keys that could address anything but a plain relative object name. Raises :class:`StorageError`."""
    if not isinstance(key, str) or not key:
        raise StorageError("invalid object key")
    if len(key) > MAX_KEY_LENGTH or key.startswith("/") or "\\" in key:
        raise StorageError("invalid object key")
    if any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in key):
        raise StorageError("invalid object key")
    if any(segment in ("", ".", "..") for segment in key.split("/")):
        raise StorageError("invalid object key")


class Storage(ABC):
    """One object-storage contract; ``bucket`` is the namespace, ``key`` the server-generated object name."""

    @abstractmethod
    def put(self, bucket: str, key: str, data: bytes | BinaryIO, length: int | None = None) -> None:
        """Write ``data`` (bytes or a binary stream; ``length`` is the stream size when known), creating the bucket if needed."""

    @abstractmethod
    def get(self, bucket: str, key: str) -> bytes:
        """Return the whole object. Raises :class:`StorageNotFound` when absent."""

    @abstractmethod
    def iter_chunks(self, bucket: str, key: str, chunk_size: int = DEFAULT_CHUNK_SIZE) -> Iterator[bytes]:
        """Stream the object in chunks of at most ``chunk_size`` bytes. Raises :class:`StorageNotFound` when absent."""

    @abstractmethod
    def rm(self, bucket: str, key: str) -> None:
        """Remove the object. Idempotent: an absent object is not an error."""

    @abstractmethod
    def exists(self, bucket: str, key: str) -> bool:
        """True when the object exists."""

    @abstractmethod
    def size(self, bucket: str, key: str) -> int | None:
        """Object size in bytes, or ``None`` when absent."""

    @abstractmethod
    def bucket_exists(self, bucket: str) -> bool:
        """True when the bucket exists."""

    @abstractmethod
    def presigned_get_url(self, bucket: str, key: str, expires_seconds: int = DEFAULT_PRESIGN_SECONDS) -> str:
        """A time-limited GET URL. Raises :class:`StorageNotSupported` on drivers without URL access."""

    @abstractmethod
    def health(self) -> bool:
        """True when the backing store is reachable."""
