#!/usr/bin/env python3
"""Generate GORM entity structs (internal/entity/*.go) from conf/schema.json, the Peewee export.

The Python engine owns the schema (D-10); the Go structs are mapped from the exported JSON and are
never hand-written (D-11). Output is gofmt-compatible and deterministic. `--check` fails on drift.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
HEADER = "// Code generated by scripts/gen_go_entities.py from conf/schema.json; DO NOT EDIT.\n\n"

# Struct names that the generic rule (split on "_", capitalise, upper-case initialisms) cannot derive
# because the table name carries digits glued to words. Documented in the plan 01-11 SUMMARY.
STRUCT_OVERRIDES = {
    "api_4_conversation": "API4Conversation",
    "connector2kb": "Connector2KB",
    "file2document": "File2Document",
}
INITIALISMS = {"id": "ID", "api": "API", "llm": "LLM", "mcp": "MCP", "kb": "KB", "url": "URL"}

STRING_TYPES = {"varchar", "char", "text", "tinytext", "mediumtext", "longtext"}
INT32_TYPES = {"tinyint", "smallint", "mediumint", "int", "integer"}
FLOAT_TYPES = {"float", "double"}
TIME_TYPES = {"datetime", "timestamp"}


class GenError(ValueError):
    """Raised for schema content the generator cannot map."""


def camel(name: str) -> str:
    parts = [p for p in name.split("_") if p]
    return "".join(INITIALISMS.get(p, p[:1].upper() + p[1:]) for p in parts)


def struct_name(table: str) -> str:
    return STRUCT_OVERRIDES.get(table) or camel(table)


def go_type(mysql_type: str, nullable: bool) -> str:
    """Map a MySQL column type to a Go type; nullable columns become pointers so NULL scans cleanly."""
    m = re.fullmatch(r"([a-z]+)(?:\((\d+)\))?", mysql_type.strip().lower())
    if not m:
        raise GenError(f"unmapped MySQL type: {mysql_type!r}")
    base, width = m.group(1), m.group(2)
    if base in STRING_TYPES:
        base_type = "string"
    elif base == "tinyint" and width == "1":
        base_type = "bool"
    elif base in INT32_TYPES:
        base_type = "int32"
    elif base == "bigint":
        base_type = "int64"
    elif base in FLOAT_TYPES:
        base_type = "float64"
    elif base in TIME_TYPES:
        base_type = "time.Time"
    else:
        raise GenError(f"unmapped MySQL type: {mysql_type!r}")
    return "*" + base_type if nullable else base_type


def _tag(col: dict[str, Any]) -> str:
    gorm = [f"column:{col['name']}"]
    if col["primary_key"]:
        gorm.append("primaryKey")
        if not col["auto_increment"]:
            gorm.append("autoIncrement:false")
    if not col["nullable"]:
        gorm.append("not null")
    return f'`gorm:"{";".join(gorm)}" json:"{col["name"]}"`'


def render_table(table: dict[str, Any]) -> str:
    name = struct_name(table["name"])
    rows: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for col in table["columns"]:
        field = camel(col["name"])
        if field in seen:
            raise GenError(f"{table['name']}: duplicate Go field {field}")
        seen.add(field)
        rows.append((field, go_type(col["type"], col["nullable"]), _tag(col)))
    nw = max(len(r[0]) for r in rows)
    tw = max(len(r[1]) for r in rows)
    needs_time = any("time.Time" in r[1] for r in rows)
    out = [HEADER, "package entity\n\n"]
    if needs_time:
        out.append('import "time"\n\n')
    out.append(f"// {name} maps the {table['name']} table.\n")
    out.append(f"type {name} struct {{\n")
    for field, typ, tag in rows:
        out.append(f"\t{field.ljust(nw)} {typ.ljust(tw)} {tag}\n")
    out.append("}\n\n")
    out.append(f"// TableName returns the exact table name.\nfunc ({name}) TableName() string {{ return \"{table['name']}\" }}\n")
    return "".join(out)


def render_registry(tables: list[dict[str, Any]]) -> str:
    out = [HEADER, "// Package entity holds the GORM mappings of the tables the Python engine owns.\n",
           "// They are read-only mappings: Go never creates or alters a table (D-10).\npackage entity\n\n",
           "// All lists one zero value of every entity, for schema verification.\nfunc All() []any {\n\treturn []any{\n"]
    for t in tables:
        out.append(f"\t\t{struct_name(t['name'])}{{}},\n")
    out.append("\t}\n}\n")
    return "".join(out)


def outputs(root: Path, out_root: Path) -> dict[Path, str]:
    data = json.loads((root / "conf" / "schema.json").read_text(encoding="utf-8"))
    tables = sorted(data["tables"], key=lambda t: t["name"])
    base = out_root / "internal" / "entity"
    files = {base / f"{t['name']}.go": render_table(t) for t in tables}
    files[base / "registry.go"] = render_registry(tables)
    return files


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed outputs differ")
    ap.add_argument("--root", default=str(REPO), help="repo root containing conf/schema.json")
    ap.add_argument("--out-root", default=None, help="write outputs under this root (tests)")
    args = ap.parse_args(argv)
    root = Path(args.root)
    out_root = Path(args.out_root) if args.out_root else root
    try:
        files = outputs(root, out_root)
    except (GenError, KeyError, OSError, json.JSONDecodeError) as exc:
        print(f"gen_go_entities: {exc}", file=sys.stderr)
        return 2
    if args.check:
        drift = False
        for path, text in files.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != text:
                drift = True
                sys.stdout.writelines(difflib.unified_diff(current.splitlines(True), text.splitlines(True),
                                                           f"{path} (disk)", f"{path} (generated)"))
        entity_dir = out_root / "internal" / "entity"
        if entity_dir.is_dir():
            for stray in sorted(set(entity_dir.glob("*.go")) - set(files)):
                drift = True
                print(f"stray file not produced by the generator: {stray}")
        if drift:
            print("gen_go_entities: generated files drifted; run `make gen`", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
