#!/usr/bin/env python3
"""Generate Nginx locations, the Vite proxy JSON and the Go and Python route-policy and permission modules from conf/routes.yaml and conf/permissions.yaml."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/gen_routes.py from conf/routes.yaml - do not edit\n"
OWNERS = {"go", "python"}
MATCHES = {"exact", "prefix"}
AUTHS = {"none", "jwt", "beta", "api"}
WEB_ROOT = "/ragflow/web/dist"
# Request-size and timeout policy of the generated locations (WR-04, R-130). Go-owned routes take small JSON documents and
# answer quickly; a route lists `body_limit` (for example /v1/user/ for the 256 KB avatar) or `streaming: true` to opt out.
# Python-owned locations keep the upload allowance and long timeouts until upload routes exist and narrow them.
GO_BODY_LIMIT = "16k"
PY_BODY_LIMIT = "1024m"
SHORT_TIMEOUT = "60s"
LONG_TIMEOUT = "3600s"
BODY_LIMIT_RE = re.compile(r"^[1-9][0-9]{0,5}[km]$")
# Keys of an expanded route that only Nginx uses; they stay out of the Vite proxy JSON.
NGINX_ONLY = ("bodyLimit", "streaming")
# Path placeholder that carries a credential: the location serving it must not log its request line (WR-03).
CREDENTIAL_PLACEHOLDER = "{token}"
METHODS = {"GET", "POST", "PATCH", "PUT", "DELETE"}
SCOPES = {"none", "tenant"}
ROLES = {"owner", "admin", "normal", "invite", "self"}
ROW_FIELDS = {"method", "path", "owner", "auth", "roles", "scope", "implemented", "note"}
REQUIRED_FIELDS = ROW_FIELDS - {"note"}
GO_POLICY = "internal/common/route_policy_gen.go"
PY_POLICY = "api/apps/route_policy_gen.py"
POLICY_HEADER = "generated by scripts/gen_routes.py, do not edit"
GO_PERMS = "internal/common/permissions_gen.go"
PY_PERMS = "api/apps/permissions_gen.py"
# Subjects of the permission table: the three workspace roles and the two credential classes. The pending
# invitation role `invite` is never a subject (D-26).
SUBJECTS = ("owner", "admin", "normal", "beta_token", "api_token")
DOC_AREAS = {"datasets", "agent_canvas", "search_bots", "mcp_server", "tenant_settings", "team_admin", "enterprise_admin"}
PERM_FIELDS = {"area", "action", "description", "allow", "enforced_in"}
NAME_RE = re.compile(r"^[a-z][a-z0-9_]{0,63}$")


class RouteError(ValueError):
    """Raised when routes.yaml is invalid."""


def load(path: Path) -> tuple[dict[str, int], list[dict[str, Any]]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    ports = data.get("ports") or {}
    for key in ("python_api", "go_api"):
        if not isinstance(ports.get(key), int):
            raise RouteError(f"ports.{key} must be an integer")
    expanded: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for raw in data.get("routes") or []:
        owner, match, auth = raw.get("owner"), raw.get("match"), raw.get("auth", "jwt")
        if owner not in OWNERS:
            raise RouteError(f"unknown owner {owner!r} for {raw.get('path')}")
        if match not in MATCHES:
            raise RouteError(f"unknown match {match!r} for {raw.get('path')}")
        if auth not in AUTHS:
            raise RouteError(f"unknown auth {auth!r} for {raw.get('path')}")
        for p in [raw["path"], *raw.get("also", [])]:
            if not p.startswith("/"):
                raise RouteError(f"path must start with /: {p}")
            if match == "prefix" and not p.endswith("/"):
                raise RouteError(f"prefix path must end with /: {p}")
            key = (match, p)
            if key in seen:
                raise RouteError(f"duplicate route {match} {p}")
            seen.add(key)
            body_limit = raw.get("body_limit", GO_BODY_LIMIT if owner == "go" else PY_BODY_LIMIT)
            if not isinstance(body_limit, str) or not BODY_LIMIT_RE.fullmatch(body_limit):
                raise RouteError(f"body_limit must look like 16k or 1024m for {p}")
            streaming = raw.get("streaming", owner == "python")
            if not isinstance(streaming, bool):
                raise RouteError(f"streaming must be a boolean for {p}")
            expanded.append(
                {
                    "owner": owner, "match": match, "path": p, "auth": auth, "publicUntilPhase": raw.get("public_until_phase"),
                    "port": ports["python_api"] if owner == "python" else ports["go_api"], "bodyLimit": body_limit, "streaming": streaming,
                }
            )
    return ports, expanded


def _family_for(path: str, routes: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Exact family entry, else the longest prefix family entry (same precedence as Nginx and the resolvers)."""
    for r in routes:
        if r["match"] == "exact" and r["path"] == path:
            return r
    best = [r for r in routes if r["match"] == "prefix" and path.startswith(r["path"])]
    return max(best, key=lambda r: len(r["path"]), default=None)


def load_endpoints(path: Path, routes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Validate the endpoints registry against the family list and return its rows."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for raw in data.get("endpoints") or []:
        where = f"{raw.get('method')} {raw.get('path')}"
        if set(raw) - ROW_FIELDS:
            raise RouteError(f"unknown field(s) {sorted(set(raw) - ROW_FIELDS)} in endpoint {where}")
        if REQUIRED_FIELDS - set(raw):
            raise RouteError(f"missing field(s) {sorted(REQUIRED_FIELDS - set(raw))} in endpoint {where}")
        if raw["method"] not in METHODS:
            raise RouteError(f"unknown method in endpoint {where}")
        if not isinstance(raw["path"], str) or not raw["path"].startswith("/"):
            raise RouteError(f"endpoint path must start with /: {where}")
        if raw["owner"] not in OWNERS:
            raise RouteError(f"unknown owner in endpoint {where}")
        if raw["auth"] not in AUTHS:
            raise RouteError(f"unknown auth in endpoint {where}")
        if raw["scope"] not in SCOPES:
            raise RouteError(f"unknown scope in endpoint {where}")
        if not isinstance(raw["roles"], list) or not set(raw["roles"]) <= ROLES:
            raise RouteError(f"unknown role in endpoint {where}")
        if not isinstance(raw["implemented"], bool):
            raise RouteError(f"implemented must be a boolean in endpoint {where}")
        key = (raw["method"], raw["path"])
        if key in seen:
            raise RouteError(f"duplicate endpoint {where}")
        seen.add(key)
        family = _family_for(re.sub(r"\{[^/{}]+\}", "x", raw["path"]), routes)
        if family is None:
            raise RouteError(f"endpoint {where} is matched by no route family")
        if family["owner"] != raw["owner"]:
            raise RouteError(f"endpoint {where} owner {raw['owner']} disagrees with family {family['path']}")
        if family["auth"] != raw["auth"]:
            raise RouteError(f"endpoint {where} auth {raw['auth']} disagrees with family {family['path']}")
        rows.append({k: raw[k] for k in sorted(REQUIRED_FIELDS)})
    return rows


def load_permissions(path: Path) -> list[dict[str, Any]]:
    """Validate conf/permissions.yaml and return its rows sorted by (area, action)."""
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if tuple(data.get("subjects") or ()) != SUBJECTS:
        raise RouteError(f"subjects must be exactly {list(SUBJECTS)} (the pending role `invite` is never a subject)")
    raw_rows = data.get("permissions")
    if not isinstance(raw_rows, list) or not raw_rows:
        raise RouteError("permissions must be a non-empty list")
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for raw in raw_rows:
        if not isinstance(raw, dict):
            raise RouteError("a permission row must be a mapping")
        where = f"{raw.get('area')}/{raw.get('action')}"
        if set(raw) - PERM_FIELDS:
            raise RouteError(f"unknown field(s) {sorted(set(raw) - PERM_FIELDS)} in permission {where}")
        if PERM_FIELDS - set(raw):
            raise RouteError(f"missing field(s) {sorted(PERM_FIELDS - set(raw))} in permission {where}")
        for key in ("area", "action"):
            if not isinstance(raw[key], str) or not NAME_RE.match(raw[key]):
                raise RouteError(f"{key} must be a lower snake_case name in permission {where}")
        if not isinstance(raw["allow"], list) or not set(raw["allow"]) <= set(SUBJECTS) or len(set(raw["allow"])) != len(raw["allow"]):
            raise RouteError(f"allow must be a list of distinct subjects from {list(SUBJECTS)} in permission {where}")
        if not isinstance(raw["enforced_in"], str) or not raw["enforced_in"].strip():
            raise RouteError(f"enforced_in must name the plan or phase in permission {where}")
        if not isinstance(raw["description"], str) or not raw["description"].strip():
            raise RouteError(f"description must be text in permission {where}")
        key2 = (raw["area"], raw["action"])
        if key2 in seen:
            raise RouteError(f"duplicate permission {where}")
        seen.add(key2)
        rows.append({"area": raw["area"], "action": raw["action"], "allow": [s for s in SUBJECTS if s in raw["allow"]]})
    missing = DOC_AREAS - {r["area"] for r in rows}
    if missing:
        raise RouteError(f"documented area(s) missing from the permission table: {sorted(missing)}")
    return sorted(rows, key=lambda r: (r["area"], r["action"]))


GO_PERMS_HEAD = """// Code generated by scripts/gen_routes.py from conf/permissions.yaml; DO NOT EDIT. ({header})

package common

// PermissionRow is one (area, action) row of the permission matrix and the subjects allowed to perform it.
type PermissionRow struct {{
	Area, Action string
	Allow        []string
}}

var permissionRows = []PermissionRow{{
"""

GO_PERMS_TAIL = """}

// PermissionRows returns a copy of the generated matrix (tests compare it with the Python table).
func PermissionRows() []PermissionRow {
	out := make([]PermissionRow, len(permissionRows))
	for i, r := range permissionRows {
		out[i] = PermissionRow{Area: r.Area, Action: r.Action, Allow: append([]string(nil), r.Allow...)}
	}
	return out
}

// Allowed reports whether subject (owner, admin, normal, beta_token or api_token) may perform action in
// area. Everything not listed is denied: unknown subjects (including the pending role "invite"), areas
// and actions all return false (D-26).
func Allowed(subject, area, action string) bool {
	for _, r := range permissionRows {
		if r.Area != area || r.Action != action {
			continue
		}
		for _, s := range r.Allow {
			if s == subject {
				return true
			}
		}
		return false
	}
	return false
}
"""


def render_go_permissions(rows: list[dict[str, Any]]) -> str:
    q = json.dumps
    out = [GO_PERMS_HEAD.format(header=POLICY_HEADER)]
    for r in rows:
        allow = ", ".join(q(x) for x in r["allow"])
        out.append(f"\t{{{q(r['area'])}, {q(r['action'])}, []string{{{allow}}}}},\n")
    out.append(GO_PERMS_TAIL)
    return "".join(out)


PY_PERMS_HEAD = '''"""Permission matrix, {header}. Source: conf/permissions.yaml."""
from __future__ import annotations

# (area, action) -> subjects allowed. Anything not listed is denied.
_ROWS: dict[tuple[str, str], tuple[str, ...]] = {{
'''

PY_PERMS_TAIL = '''}


def rows() -> dict[tuple[str, str], tuple[str, ...]]:
    """A copy of the matrix (tests compare it with the Go table)."""
    return dict(_ROWS)


def allowed(subject: str, area: str, action: str) -> bool:
    """True only for a listed (area, action) whose allow list names subject. Unknown subjects (including the
    pending role `invite`), areas and actions are denied (D-26)."""
    return subject in _ROWS.get((area, action), ())
'''


def render_py_permissions(rows: list[dict[str, Any]]) -> str:
    out = [PY_PERMS_HEAD.format(header=POLICY_HEADER)]
    for r in rows:
        out.append(f"    ({r['area']!r}, {r['action']!r}): {tuple(r['allow'])!r},\n")
    out.append(PY_PERMS_TAIL)
    return "".join(out)


def _policy_tables(routes: list[dict[str, Any]], rows: list[dict[str, Any]]):
    exact = sorted((r["path"], r["owner"], r["auth"]) for r in routes if r["match"] == "exact")
    prefix = sorted(((r["path"], r["owner"], r["auth"]) for r in routes if r["match"] == "prefix"), key=lambda t: (-len(t[0]), t[0]))
    return exact, prefix, sorted(rows, key=lambda r: (r["path"], r["method"]))


GO_TAIL = """}

func rowMatches(segments []string, path string) bool {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	if len(parts) != len(segments) {
		return false
	}
	for i, seg := range segments {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			if parts[i] == "" {
				return false
			}
			continue
		}
		if seg != parts[i] {
			return false
		}
	}
	return true
}

// PolicyFor resolves the access policy: registry row (method and path), then exact family entry,
// then longest prefix family entry, then the default (jwt, no owner). It never yields auth "none" by omission.
func PolicyFor(method, path string) RoutePolicy {
	preflight := method == "OPTIONS"
	if !preflight {
		for _, row := range policyRows {
			if row.method == method && rowMatches(row.segments, path) {
				return RoutePolicy{Auth: row.auth, Roles: row.roles, Scope: row.scope, Owner: row.owner}
			}
		}
	}
	for _, f := range policyExact {
		if f.path == path {
			return RoutePolicy{Auth: f.auth, Roles: []string{}, Scope: "none", Owner: f.owner, Preflight: preflight}
		}
	}
	for _, f := range policyPrefix {
		if strings.HasPrefix(path, f.path) {
			return RoutePolicy{Auth: f.auth, Roles: []string{}, Scope: "none", Owner: f.owner, Preflight: preflight}
		}
	}
	return RoutePolicy{Auth: "jwt", Roles: []string{}, Scope: "none", Owner: "", Preflight: preflight}
}
"""

GO_HEAD = """// Code generated by scripts/gen_routes.py from conf/routes.yaml; DO NOT EDIT. ({header})

package common

import "strings"

// RoutePolicy is the resolved access policy for one request. Unmatched paths resolve to Auth "jwt" (default deny).
type RoutePolicy struct {{
	Auth      string
	Roles     []string
	Scope     string
	Owner     string
	Preflight bool
}}

type policyFamily struct{{ path, owner, auth string }}

type policyRow struct {{
	method, owner, auth, scope string
	segments                   []string
	roles                      []string
}}

"""


def render_go_policy(routes: list[dict[str, Any]], rows: list[dict[str, Any]]) -> str:
    exact, prefix, rws = _policy_tables(routes, rows)
    q = json.dumps
    out = [GO_HEAD.format(header=POLICY_HEADER), "var policyExact = []policyFamily{\n"]
    out += [f"\t{{{q(p)}, {q(o)}, {q(a)}}},\n" for p, o, a in exact]
    out.append("}\n\nvar policyPrefix = []policyFamily{\n")
    out += [f"\t{{{q(p)}, {q(o)}, {q(a)}}},\n" for p, o, a in prefix]
    out.append("}\n\nvar policyRows = []policyRow{\n")
    for r in rws:
        segs = ", ".join(q(x) for x in r["path"].split("/")[1:])
        roles = ", ".join(q(x) for x in r["roles"])
        out.append(f"\t{{{q(r['method'])}, {q(r['owner'])}, {q(r['auth'])}, {q(r['scope'])}, []string{{{segs}}}, []string{{{roles}}}}},\n")
    out.append(GO_TAIL)
    return "".join(out)


PY_HEAD = '''"""Route policy resolver, {header}. Source: conf/routes.yaml."""
from __future__ import annotations

from typing import NamedTuple


class RoutePolicy(NamedTuple):
    """Resolved access policy. Unmatched paths resolve to auth jwt (default deny)."""

    auth: str
    roles: tuple[str, ...]
    scope: str
    owner: str
    preflight: bool


'''

PY_TAIL = '''

def _row_matches(segments: tuple[str, ...], path: str) -> bool:
    parts = path.removeprefix("/").split("/")
    if len(parts) != len(segments):
        return False
    for seg, part in zip(segments, parts, strict=True):
        if seg.startswith("{") and seg.endswith("}"):
            if not part:
                return False
        elif seg != part:
            return False
    return True


def policy_for(method: str, path: str) -> RoutePolicy:
    """Registry row (method and path), then exact family, then longest prefix family, then default jwt (deny)."""
    preflight = method == "OPTIONS"
    if not preflight:
        for row_method, segments, owner, auth, scope, roles in _ROWS:
            if row_method == method and _row_matches(segments, path):
                return RoutePolicy(auth, roles, scope, owner, False)
    if path in _EXACT:
        owner, auth = _EXACT[path]
        return RoutePolicy(auth, (), "none", owner, preflight)
    for prefix, owner, auth in _PREFIX:
        if path.startswith(prefix):
            return RoutePolicy(auth, (), "none", owner, preflight)
    return RoutePolicy("jwt", (), "none", "", preflight)
'''


def render_py_policy(routes: list[dict[str, Any]], rows: list[dict[str, Any]]) -> str:
    exact, prefix, rws = _policy_tables(routes, rows)
    out = [PY_HEAD.format(header=POLICY_HEADER), "_EXACT: dict[str, tuple[str, str]] = {\n"]
    out += [f"    {p!r}: ({o!r}, {a!r}),\n" for p, o, a in exact]
    out.append("}\n\n_PREFIX: tuple[tuple[str, str, str], ...] = (\n")
    out += [f"    ({p!r}, {o!r}, {a!r}),\n" for p, o, a in prefix]
    out.append(")\n\n_ROWS: tuple[tuple[str, tuple[str, ...], str, str, str, tuple[str, ...]], ...] = (\n")
    for r in rws:
        segs = tuple(r["path"].split("/")[1:])
        out.append(f"    ({r['method']!r}, {segs!r}, {r['owner']!r}, {r['auth']!r}, {r['scope']!r}, {tuple(r['roles'])!r}),\n")
    out.append(")\n")
    out.append(PY_TAIL)
    return "".join(out)


def _ordered(routes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    exact = sorted((r for r in routes if r["match"] == "exact"), key=lambda r: r["path"])
    prefix = sorted((r for r in routes if r["match"] == "prefix"), key=lambda r: (-len(r["path"]), r["path"]))
    return exact + prefix


def credential_prefixes(rows: list[dict[str, Any]]) -> set[str]:
    """Route paths whose registry rows carry a credential in the URL, for example /api/v1/system/tokens/{token}."""
    return {r["path"].split(CREDENTIAL_PLACEHOLDER, 1)[0] for r in rows if CREDENTIAL_PLACEHOLDER in r["path"]}


def _location(r: dict[str, Any], credential: set[str]) -> str:
    op = "=" if r["match"] == "exact" else "^~"
    timeout = LONG_TIMEOUT if r["streaming"] else SHORT_TIMEOUT
    lines = [
        f"        proxy_pass http://127.0.0.1:{r['port']};",
        f"        client_max_body_size {r['bodyLimit']};",
        f"        proxy_read_timeout {timeout};",
        f"        proxy_send_timeout {timeout};",
    ]
    if r["path"] in credential:
        # An upstream failure writes `request: "<method> <target> ..."` to the error log at error level, and the target
        # of this family holds a live API token. Only emergencies are written for these locations (WR-03).
        lines.append("        error_log /dev/stderr emerg;")
    lines.append("        include proxy.conf;")
    return f"    location {op} {r['path']} {{\n" + "\n".join(lines) + "\n    }\n"


def _locations(routes: list[dict[str, Any]], credential: set[str]) -> str:
    out: list[str] = [_location(r, credential) for r in _ordered(routes)]
    out.append(f"""    location /assets/ {{
        root {WEB_ROOT};
        expires 1y;
        add_header Cache-Control "public, immutable";
    }}

    location = /index.html {{
        root {WEB_ROOT};
        add_header Cache-Control "no-cache";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
    }}

    location / {{
        root {WEB_ROOT};
        try_files $uri $uri/ /index.html;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
    }}
""")
    return "\n".join(out)


# Nginx answers an oversized body with an HTML page; API clients expect the envelope (code 400, as the Go server sends).
PAYLOAD_TOO_LARGE = """    error_page 413 @payload_too_large;

    location @payload_too_large {
        default_type application/json;
        return 413 '{"code":400,"message":"payload too large","data":null}';
    }

"""


def render_http(routes: list[dict[str, Any]], credential: set[str]) -> str:
    return f"{HEADER}server {{\n    listen 80;\n    server_name _;\n\n{PAYLOAD_TOO_LARGE}{_locations(routes, credential)}}}\n"


def render_https(routes: list[dict[str, Any]], credential: set[str]) -> str:
    return (
        f"{HEADER}server {{\n    listen 80;\n    server_name _;\n    return 301 https://$host$request_uri;\n}}\n\n"
        f"server {{\n    listen 443 ssl;\n    server_name _;\n"
        f"    ssl_certificate /etc/nginx/certs/server.crt;\n    ssl_certificate_key /etc/nginx/certs/server.key;\n"
        f"    ssl_protocols TLSv1.2 TLSv1.3;\n\n{PAYLOAD_TOO_LARGE}{_locations(routes, credential)}}}\n"
    )


def render_json(ports: dict[str, int], routes: list[dict[str, Any]]) -> str:
    public = [{k: v for k, v in r.items() if k not in NGINX_ONLY} for r in _ordered(routes)]
    return json.dumps({"ports": ports, "routes": public}, indent=2) + "\n"


def outputs(root: Path, out_root: Path) -> dict[Path, str]:
    ports, routes = load(root / "conf" / "routes.yaml")
    rows = load_endpoints(root / "conf" / "routes.yaml", routes)
    perms = load_permissions(root / "conf" / "permissions.yaml")
    return {
        out_root / GO_PERMS: render_go_permissions(perms),
        out_root / PY_PERMS: render_py_permissions(perms),
        out_root / GO_POLICY: render_go_policy(routes, rows),
        out_root / PY_POLICY: render_py_policy(routes, rows),
        out_root / "docker/nginx/ragflow.conf": render_http(routes, credential_prefixes(rows)),
        out_root / "docker/nginx/ragflow.https.conf": render_https(routes, credential_prefixes(rows)),
        out_root / "web/src/constants/api-routes.generated.json": render_json(ports, routes),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed outputs differ")
    ap.add_argument("--root", default=str(REPO), help="repo root containing conf/routes.yaml")
    ap.add_argument("--out-root", default=None, help="write outputs under this root (tests)")
    args = ap.parse_args(argv)
    root = Path(args.root)
    out_root = Path(args.out_root) if args.out_root else root
    try:
        files = outputs(root, out_root)
    except (RouteError, KeyError, AttributeError, OSError, yaml.YAMLError) as exc:
        print(f"gen_routes: invalid routes.yaml or permissions.yaml: {exc}", file=sys.stderr)
        return 2
    if args.check:
        drift = False
        for path, text in files.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != text:
                drift = True
                sys.stdout.writelines(difflib.unified_diff(current.splitlines(True), text.splitlines(True), f"{path} (disk)", f"{path} (generated)"))
        if drift:
            print("gen_routes: generated files drifted; run `make gen`", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
