#!/usr/bin/env python3
"""Generate Nginx locations and the Vite proxy JSON from conf/routes.yaml (single source of route ownership)."""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/gen_routes.py from conf/routes.yaml - do not edit\n"
OWNERS = {"go", "python"}
MATCHES = {"exact", "prefix"}
AUTHS = {"none", "jwt", "beta", "api"}
WEB_ROOT = "/ragflow/web/dist"


class RouteError(ValueError):
    """Raised when routes.yaml is invalid."""


def load(path: Path) -> tuple[dict[str, int], list[dict[str, Any]]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    ports = data.get("ports") or {}
    for key in ("python_api", "go_api"):
        if not isinstance(ports.get(key), int):
            raise RouteError(f"ports.{key} must be an integer")
    expanded: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for raw in data.get("routes") or []:
        owner, match, auth = raw.get("owner"), raw.get("match"), raw.get("auth", "jwt")
        if owner not in OWNERS:
            raise RouteError(f"unknown owner {owner!r} for {raw.get('path')}")
        if match not in MATCHES:
            raise RouteError(f"unknown match {match!r} for {raw.get('path')}")
        if auth not in AUTHS:
            raise RouteError(f"unknown auth {auth!r} for {raw.get('path')}")
        for p in [raw["path"], *raw.get("also", [])]:
            if not p.startswith("/"):
                raise RouteError(f"path must start with /: {p}")
            if match == "prefix" and not p.endswith("/"):
                raise RouteError(f"prefix path must end with /: {p}")
            key = (match, p)
            if key in seen:
                raise RouteError(f"duplicate route {match} {p}")
            seen.add(key)
            expanded.append({"owner": owner, "match": match, "path": p, "auth": auth,
                             "publicUntilPhase": raw.get("public_until_phase"),
                             "port": ports["python_api"] if owner == "python" else ports["go_api"]})
    return ports, expanded


def _ordered(routes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    exact = sorted((r for r in routes if r["match"] == "exact"), key=lambda r: r["path"])
    prefix = sorted((r for r in routes if r["match"] == "prefix"), key=lambda r: (-len(r["path"]), r["path"]))
    return exact + prefix


def _locations(routes: list[dict[str, Any]]) -> str:
    out: list[str] = []
    for r in _ordered(routes):
        op = "=" if r["match"] == "exact" else "^~"
        out.append(f"    location {op} {r['path']} {{\n"
                   f"        proxy_pass http://127.0.0.1:{r['port']};\n"
                   f"        include proxy.conf;\n    }}\n")
    out.append(f"""    location /assets/ {{
        root {WEB_ROOT};
        expires 1y;
        add_header Cache-Control "public, immutable";
    }}

    location = /index.html {{
        root {WEB_ROOT};
        add_header Cache-Control "no-cache";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
    }}

    location / {{
        root {WEB_ROOT};
        try_files $uri $uri/ /index.html;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
    }}
""")
    return "\n".join(out)


def render_http(routes: list[dict[str, Any]]) -> str:
    return (f"{HEADER}server {{\n    listen 80;\n    server_name _;\n\n{_locations(routes)}}}\n")


def render_https(routes: list[dict[str, Any]]) -> str:
    return (f"{HEADER}server {{\n    listen 80;\n    server_name _;\n    return 301 https://$host$request_uri;\n}}\n\n"
            f"server {{\n    listen 443 ssl;\n    server_name _;\n"
            f"    ssl_certificate /etc/nginx/certs/server.crt;\n    ssl_certificate_key /etc/nginx/certs/server.key;\n"
            f"    ssl_protocols TLSv1.2 TLSv1.3;\n\n{_locations(routes)}}}\n")


def render_json(ports: dict[str, int], routes: list[dict[str, Any]]) -> str:
    return json.dumps({"ports": ports, "routes": _ordered(routes)}, indent=2) + "\n"


def outputs(root: Path, out_root: Path) -> dict[Path, str]:
    ports, routes = load(root / "conf" / "routes.yaml")
    return {
        out_root / "docker/nginx/ragflow.conf": render_http(routes),
        out_root / "docker/nginx/ragflow.https.conf": render_https(routes),
        out_root / "web/src/constants/api-routes.generated.json": render_json(ports, routes),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed outputs differ")
    ap.add_argument("--root", default=str(REPO), help="repo root containing conf/routes.yaml")
    ap.add_argument("--out-root", default=None, help="write outputs under this root (tests)")
    args = ap.parse_args(argv)
    root = Path(args.root)
    out_root = Path(args.out_root) if args.out_root else root
    try:
        files = outputs(root, out_root)
    except (RouteError, KeyError, AttributeError) as exc:
        print(f"gen_routes: invalid routes.yaml: {exc}", file=sys.stderr)
        return 2
    if args.check:
        drift = False
        for path, text in files.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != text:
                drift = True
                sys.stdout.writelines(difflib.unified_diff(current.splitlines(True), text.splitlines(True),
                                                           f"{path} (disk)", f"{path} (generated)"))
        if drift:
            print("gen_routes: generated files drifted; run `make gen`", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
