"""Stable machine reason strings carried by ``ServiceError.reason`` and API error bodies.

This is the one place a reason string is spelled. Constants only, no logic; later plans add names here when they need one.
"""

PROVIDER_UNKNOWN = "provider_unknown"
PROVIDER_NOT_CONFIGURED = "provider_not_configured"
PROVIDER_REFUSED = "provider_refused"
PROVIDER_RATE_LIMITED = "provider_rate_limited"
PROVIDER_TIMEOUT = "provider_timeout"
PROVIDER_UNREACHABLE = "provider_unreachable"
KEY_STORE_UNAVAILABLE = "key_store_unavailable"
KEY_UNREADABLE = "key_unreadable"
PROVIDER_TEST_RATE_LIMITED = "provider_test_rate_limited"
RATE_LIMIT_UNAVAILABLE = "rate_limit_unavailable"
BASE_URL_REFUSED = "base_url_refused"
BASE_URL_INVALID = "base_url_invalid"
BASE_URL_REQUIRED = "base_url_required"
API_VERSION_REQUIRED = "api_version_required"
KEY_REQUIRED = "key_required"
KEY_REQUIRED_FOR_NEW_ADDRESS = "key_required_for_new_address"
MODELS_INVALID = "models_invalid"
MODEL_EXISTS = "model_exists"
MODEL_UNAVAILABLE = "model_unavailable"
DIMENSION_UNSUPPORTED = "dimension_unsupported"
DIMENSION_MISMATCH = "dimension_mismatch"
DUPLICATE_NAME = "duplicate_name"
DATASET_INVALID = "dataset_invalid"
NO_DEFAULT_EMBEDDING = "no_default_embedding"
INDEX_UNAVAILABLE = "index_unavailable"
DATASET_LIMIT = "dataset_limit"
TOO_MANY_FILES = "too_many_files"
FILE_TOO_LARGE = "file_too_large"
UNSUPPORTED_TYPE = "unsupported_type"
INVALID_FILENAME = "invalid_filename"
EMPTY_FILE = "empty_file"
NO_FILES = "no_files"
DATASET_NOT_FOUND = "dataset_not_found"
BUSY = "busy"
INSTANCE_INVALID = "instance_invalid"
OPERATION_TIMEOUT = "operation_timeout"
INSTANCE_EXISTS = "instance_exists"
