// Code generated by scripts/gen_routes.py from conf/permissions.yaml; DO NOT EDIT. (generated by scripts/gen_routes.py, do not edit)

package common

// PermissionRow is one (area, action) row of the permission matrix and the subjects allowed to perform it.
type PermissionRow struct {
	Area, Action string
	Allow        []string
}

var permissionRows = []PermissionRow{
	{"agent_canvas", "manage_flow", []string{"owner", "admin", "normal", "api_token"}},
	{"agent_canvas", "stream_completion", []string{"owner", "admin", "normal", "beta_token", "api_token"}},
	{"datasets", "manage_dataset", []string{"owner", "admin", "normal", "api_token"}},
	{"datasets", "manage_document", []string{"owner", "admin", "normal", "api_token"}},
	{"datasets", "retrieval_test", []string{"owner", "admin", "normal", "beta_token", "api_token"}},
	{"enterprise_admin", "view_health", []string{"owner", "admin"}},
	{"mcp_server", "tool_call", []string{"owner", "admin", "normal", "beta_token", "api_token"}},
	{"search_bots", "ask", []string{"owner", "admin", "normal", "beta_token", "api_token"}},
	{"team_admin", "manage_members", []string{"owner"}},
	{"tenant_settings", "update_llm_keys", []string{"owner", "admin"}},
}

// PermissionRows returns a copy of the generated matrix (tests compare it with the Python table).
func PermissionRows() []PermissionRow {
	out := make([]PermissionRow, len(permissionRows))
	for i, r := range permissionRows {
		out[i] = PermissionRow{Area: r.Area, Action: r.Action, Allow: append([]string(nil), r.Allow...)}
	}
	return out
}

// Allowed reports whether subject (owner, admin, normal, beta_token or api_token) may perform action in
// area. Everything not listed is denied: unknown subjects (including the pending role "invite"), areas
// and actions all return false (D-26).
func Allowed(subject, area, action string) bool {
	for _, r := range permissionRows {
		if r.Area != area || r.Action != action {
			continue
		}
		for _, s := range r.Allow {
			if s == subject {
				return true
			}
		}
		return false
	}
	return false
}
