// Code generated by scripts/gen_routes.py from conf/routes.yaml; DO NOT EDIT. (generated by scripts/gen_routes.py, do not edit)

package common

import "strings"

// RoutePolicy is the resolved access policy for one request. Unmatched paths resolve to Auth "jwt" (default deny).
type RoutePolicy struct {
	Auth      string
	Roles     []string
	Scope     string
	Owner     string
	Preflight bool
}

type policyFamily struct{ path, owner, auth string }

type policyRow struct {
	method, owner, auth, scope string
	segments                   []string
	roles                      []string
}

var policyExact = []policyFamily{
	{"/api/v1/auth/logout", "go", "jwt"},
	{"/api/v1/language", "go", "none"},
	{"/api/v1/mcp", "go", "beta"},
	{"/api/v1/system/config", "go", "none"},
	{"/api/v1/system/healthz", "python", "none"},
	{"/api/v1/system/ping", "go", "none"},
	{"/api/v1/system/status", "python", "jwt"},
	{"/api/v1/system/tokens", "go", "jwt"},
	{"/api/v1/system/version", "go", "jwt"},
	{"/api/v1/users", "go", "none"},
	{"/health", "go", "none"},
	{"/system/healthz", "python", "none"},
	{"/system/status", "python", "jwt"},
}

var policyPrefix = []policyFamily{
	{"/api/v1/system/tokens/", "go", "jwt"},
	{"/api/v1/searchbots/", "go", "beta"},
	{"/api/v1/tenants/", "go", "jwt"},
	{"/api/v1/auth/", "go", "none"},
	{"/v1/tenant/", "go", "jwt"},
	{"/v1/user/", "go", "jwt"},
	{"/api/", "python", "api"},
	{"/v1/", "python", "api"},
}

var policyRows = []policyRow{
	{"POST", "go", "none", "none", []string{"api", "v1", "auth", "login"}, []string{}},
	{"POST", "go", "jwt", "none", []string{"api", "v1", "auth", "logout"}, []string{}},
	{"POST", "go", "none", "none", []string{"api", "v1", "auth", "password", "forgot", "otp"}, []string{}},
	{"POST", "go", "none", "none", []string{"api", "v1", "auth", "password", "forgot", "otp", "verify"}, []string{}},
	{"POST", "go", "none", "none", []string{"api", "v1", "auth", "password", "reset"}, []string{}},
	{"GET", "go", "none", "none", []string{"api", "v1", "language"}, []string{}},
	{"GET", "python", "api", "none", []string{"api", "v1", "openapi.json"}, []string{}},
	{"POST", "go", "beta", "none", []string{"api", "v1", "searchbots", "ask"}, []string{}},
	{"POST", "go", "beta", "none", []string{"api", "v1", "searchbots", "retrieval_test"}, []string{}},
	{"GET", "go", "none", "none", []string{"api", "v1", "system", "config"}, []string{}},
	{"GET", "python", "none", "none", []string{"api", "v1", "system", "healthz"}, []string{}},
	{"GET", "go", "none", "none", []string{"api", "v1", "system", "ping"}, []string{}},
	{"GET", "python", "jwt", "none", []string{"api", "v1", "system", "status"}, []string{}},
	{"GET", "go", "jwt", "tenant", []string{"api", "v1", "system", "tokens"}, []string{"owner"}},
	{"POST", "go", "jwt", "tenant", []string{"api", "v1", "system", "tokens"}, []string{"owner"}},
	{"DELETE", "go", "jwt", "tenant", []string{"api", "v1", "system", "tokens", "{token}"}, []string{"owner"}},
	{"GET", "go", "jwt", "none", []string{"api", "v1", "system", "version"}, []string{}},
	{"PATCH", "go", "jwt", "tenant", []string{"api", "v1", "tenants", "{tenant_id}"}, []string{"invite"}},
	{"DELETE", "go", "jwt", "tenant", []string{"api", "v1", "tenants", "{tenant_id}", "users"}, []string{"owner", "self"}},
	{"GET", "go", "jwt", "tenant", []string{"api", "v1", "tenants", "{tenant_id}", "users"}, []string{"owner", "admin", "normal"}},
	{"POST", "go", "jwt", "tenant", []string{"api", "v1", "tenants", "{tenant_id}", "users"}, []string{"owner"}},
	{"PATCH", "go", "jwt", "tenant", []string{"api", "v1", "tenants", "{tenant_id}", "users", "{user_id}"}, []string{"owner"}},
	{"POST", "go", "none", "none", []string{"api", "v1", "users"}, []string{}},
	{"GET", "go", "none", "none", []string{"health"}, []string{}},
	{"GET", "python", "none", "none", []string{"system", "healthz"}, []string{}},
	{"GET", "python", "jwt", "none", []string{"system", "status"}, []string{}},
	{"GET", "go", "jwt", "none", []string{"v1", "tenant", "list"}, []string{}},
	{"GET", "go", "jwt", "none", []string{"v1", "user", "info"}, []string{}},
	{"POST", "go", "jwt", "none", []string{"v1", "user", "setting"}, []string{}},
	{"POST", "go", "jwt", "none", []string{"v1", "user", "setting", "password"}, []string{}},
	{"GET", "go", "jwt", "none", []string{"v1", "user", "tenant_info"}, []string{}},
}

func rowMatches(segments []string, path string) bool {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	if len(parts) != len(segments) {
		return false
	}
	for i, seg := range segments {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			if parts[i] == "" {
				return false
			}
			continue
		}
		if seg != parts[i] {
			return false
		}
	}
	return true
}

// PolicyFor resolves the access policy: registry row (method and path), then exact family entry,
// then longest prefix family entry, then the default (jwt, no owner). It never yields auth "none" by omission.
func PolicyFor(method, path string) RoutePolicy {
	preflight := method == "OPTIONS"
	if !preflight {
		for _, row := range policyRows {
			if row.method == method && rowMatches(row.segments, path) {
				return RoutePolicy{Auth: row.auth, Roles: row.roles, Scope: row.scope, Owner: row.owner}
			}
		}
	}
	for _, f := range policyExact {
		if f.path == path {
			return RoutePolicy{Auth: f.auth, Roles: []string{}, Scope: "none", Owner: f.owner, Preflight: preflight}
		}
	}
	for _, f := range policyPrefix {
		if strings.HasPrefix(path, f.path) {
			return RoutePolicy{Auth: f.auth, Roles: []string{}, Scope: "none", Owner: f.owner, Preflight: preflight}
		}
	}
	return RoutePolicy{Auth: "jwt", Roles: []string{}, Scope: "none", Owner: "", Preflight: preflight}
}
