"""Live schema checks on a scratch database: 38 tables from empty, documented DDL, indexes (DATA-01/02/05/06)."""
from __future__ import annotations

import json
import re
import shutil
from collections import defaultdict
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from api.db.database import DB, init_database
from api.db.migrations.runner import DEFAULT_MIGRATIONS_DIR, current_version, run_migrations
from test.conftest import REPO_ROOT
from test.helpers.db import app_connection_settings, scratch_database

pytestmark = pytest.mark.integration

SCHEMA_MD = REPO_ROOT / "docs" / "08-database" / "schema.md"
SCHEMA_JSON = REPO_ROOT / "conf" / "schema.json"
DOCUMENTED_INDEX_COLUMNS = [
    ("document", ("kb_id",)), ("document", ("parser_id",)), ("document", ("status",)),
    ("task", ("doc_id",)), ("task", ("progress",)), ("knowledgebase", ("tenant_id",)), ("file", ("parent_id",)),
]  # fmt: skip


@pytest.fixture(scope="module")
def live() -> Iterator[dict[str, Any]]:
    with scratch_database() as name:
        database = init_database(app_connection_settings(name))
        try:
            first = run_migrations()
            second = run_migrations()
            with DB.connection_context():
                version = current_version()
            yield {"db": name, "first": first, "second": second, "version": version}
        finally:
            database.close_all()
            DB.initialize(None)


def _query(db_name: str, sql: str) -> list[tuple[Any, ...]]:
    with DB.connection_context():
        return [tuple(r) for r in DB.execute_sql(sql, (db_name,)).fetchall()]


def _text(value: Any) -> Any:
    return value.decode() if isinstance(value, bytes) else value


def _columns(db_name: str, table: str | None = None) -> dict[str, dict[str, dict[str, Any]]]:
    rows = _query(db_name, "SELECT table_name, column_name, column_type, is_nullable, column_default FROM information_schema.columns WHERE table_schema = %s")
    out: dict[str, dict[str, dict[str, Any]]] = defaultdict(dict)
    for t, c, ctype, nullable, default in rows:
        out[_text(t)][_text(c)] = {"type": _text(ctype), "nullable": _text(nullable) == "YES", "default": _text(default)}
    return out


def parse_documented_ddl(markdown: str) -> dict[str, dict[str, Any]]:
    """Parse the CREATE TABLE statements in schema.md into columns and index definitions."""
    tables: dict[str, dict[str, Any]] = {}
    for block in re.findall(r"```sql\n(.*?)```", markdown, re.S):
        match = re.search(r"CREATE TABLE `(\w+)` \((.*)\);", block, re.S)
        if not match:
            continue
        columns: dict[str, dict[str, Any]] = {}
        indexes: dict[str, tuple[str, ...]] = {}
        for raw in match.group(2).splitlines():
            line = raw.strip().rstrip(",")
            if not line:
                continue
            idx = re.match(r"INDEX `(\w+)` \(`(\w+)`\)$", line)
            if idx:
                indexes[idx.group(1)] = (idx.group(2),)
                continue
            col = re.match(r"`(\w+)` (\w+(?:\(\d+\))?)(.*)$", line)
            assert col, f"unparsed DDL line: {line}"
            rest = col.group(3)
            default = re.search(r"DEFAULT ('([^']*)'|\S+)", rest)
            primary = "PRIMARY KEY" in rest
            columns[col.group(1)] = {
                "type": col.group(2),
                "nullable": "NOT NULL" not in rest and not primary,
                "default": None if not default else (default.group(2) if default.group(2) is not None else default.group(1)),
            }
        tables[match.group(1)] = {"columns": columns, "indexes": indexes}
    return tables


def test_documented_ddl_parser_finds_the_three_tables() -> None:
    parsed = parse_documented_ddl(SCHEMA_MD.read_text(encoding="utf-8"))
    assert set(parsed) == {"document", "task", "knowledgebase"}
    assert parsed["document"]["columns"]["kb_id"] == {"type": "varchar(256)", "nullable": False, "default": None}
    assert parsed["document"]["columns"]["run"] == {"type": "varchar(1)", "nullable": True, "default": "0"}


def test_empty_database_gets_38_tables_and_version_0002(live: dict[str, Any]) -> None:
    tables = {_text(r[0]) for r in _query(live["db"], "SELECT table_name FROM information_schema.tables WHERE table_schema = %s")}
    assert len(tables) == 38
    assert live["first"] == ["0001", "0002"]
    assert live["version"] == 2
    with DB.connection_context():
        stored = DB.execute_sql("SELECT value FROM " + live["db"] + ".system_settings WHERE name = 'schema.version'").fetchall()  # noqa: S608 - scratch name is generated by the helper
    assert _text(stored[0][0]) == "0002"


def test_second_run_applies_nothing(live: dict[str, Any]) -> None:
    assert live["second"] == []


def test_documented_secondary_indexes_exist_by_column_coverage(live: dict[str, Any]) -> None:
    rows = _query(live["db"], "SELECT table_name, index_name, column_name FROM information_schema.statistics WHERE table_schema = %s ORDER BY table_name, index_name, seq_in_index")
    by_index: dict[tuple[str, str], list[str]] = defaultdict(list)
    for t, i, c in rows:
        by_index[(_text(t), _text(i))].append(_text(c))
    for table, columns in DOCUMENTED_INDEX_COLUMNS:
        assert list(columns) in [v for (t, _), v in by_index.items() if t == table], f"missing index on {table}{columns}"


def test_documented_index_names_exist(live: dict[str, Any]) -> None:
    documented = parse_documented_ddl(SCHEMA_MD.read_text(encoding="utf-8"))
    rows = _query(live["db"], "SELECT table_name, index_name FROM information_schema.statistics WHERE table_schema = %s")
    present = {(_text(t), _text(i)) for t, i in rows}
    for table, spec in documented.items():
        for name in spec["indexes"]:
            assert (table, name) in present, f"{table}.{name}"


@pytest.mark.parametrize("table", ["document", "task", "knowledgebase"])
def test_documented_tables_match_schema_md(live: dict[str, Any], table: str) -> None:
    documented = parse_documented_ddl(SCHEMA_MD.read_text(encoding="utf-8"))[table]["columns"]
    actual = _columns(live["db"])[table]
    for name, want in documented.items():
        assert name in actual, f"{table}.{name} missing"
        assert actual[name]["type"] == want["type"], f"{table}.{name} type {actual[name]['type']} != {want['type']}"
        assert actual[name]["nullable"] == want["nullable"], f"{table}.{name} nullability"
        assert actual[name]["default"] == want["default"], f"{table}.{name} default {actual[name]['default']!r} != {want['default']!r}"


def test_no_tenant_id_on_document_or_task(live: dict[str, Any]) -> None:
    actual = _columns(live["db"])
    assert "tenant_id" not in actual["document"]
    assert "tenant_id" not in actual["task"]
    assert "tenant_id" in actual["knowledgebase"]


def test_user_email_unique_at_baseline(live: dict[str, Any]) -> None:
    rows = _query(live["db"], "SELECT non_unique FROM information_schema.statistics WHERE table_schema = %s AND table_name = 'user' AND column_name = 'email'")
    assert rows
    assert all(int(r[0]) == 0 for r in rows)


def test_live_columns_match_committed_schema_json(live: dict[str, Any]) -> None:
    exported = {t["name"]: t for t in json.loads(SCHEMA_JSON.read_text(encoding="utf-8"))["tables"]}
    actual = _columns(live["db"])
    assert set(actual) == set(exported)
    for table, spec in exported.items():
        assert set(actual[table]) == {c["name"] for c in spec["columns"]}, table
        for col in spec["columns"]:
            got = actual[table][col["name"]]
            assert got["type"] == col["type"], f"{table}.{col['name']} type"
            assert got["nullable"] == col["nullable"], f"{table}.{col['name']} nullable"
            assert got["default"] == col["default"], f"{table}.{col['name']} default"


def test_live_indexes_match_committed_schema_json(live: dict[str, Any]) -> None:
    rows = _query(live["db"], "SELECT table_name, index_name, column_name FROM information_schema.statistics WHERE table_schema = %s ORDER BY table_name, index_name, seq_in_index")
    actual: dict[tuple[str, str], list[str]] = defaultdict(list)
    for t, i, c in rows:
        actual[(_text(t), _text(i))].append(_text(c))
    for table in json.loads(SCHEMA_JSON.read_text(encoding="utf-8"))["tables"]:
        for index in table["indexes"]:
            assert actual.get((table["name"], index["name"])) == index["columns"], f"{table['name']}.{index['name']}"


def test_extra_migration_in_temp_dir_applies_once(tmp_path: Path) -> None:
    for source in DEFAULT_MIGRATIONS_DIR.glob("000[12]_*.py"):
        shutil.copy(source, tmp_path / source.name)
    (tmp_path / "0003_marker.py").write_text(
        'VERSION = "0003"\n\ndef upgrade(db):\n    db.execute_sql("CREATE TABLE IF NOT EXISTS marker_three (id INT PRIMARY KEY)")\n',
        encoding="utf-8",
    )
    with scratch_database() as name:
        database = init_database(app_connection_settings(name))
        try:
            assert run_migrations(migrations_dir=tmp_path) == ["0001", "0002", "0003"]
            assert run_migrations(migrations_dir=tmp_path) == []
            with DB.connection_context():
                assert current_version() == 3
        finally:
            database.close_all()
            DB.initialize(None)


def test_rerun_after_partial_baseline_adds_missing_index_and_tables() -> None:
    """R-75: an interrupted 0002 (one table dropped, one index dropped) is repaired by a rerun."""
    with scratch_database() as name:
        database = init_database(app_connection_settings(name))
        try:
            run_migrations()
            with DB.connection_context():
                DB.execute_sql("DROP TABLE `memory`")
                DB.execute_sql("ALTER TABLE `document` DROP INDEX `idx_doc_kb_id`")
                DB.execute_sql("UPDATE system_settings SET value = '0001' WHERE name = 'schema.version'")
            assert run_migrations() == ["0002"]
            tables = {_text(r[0]) for r in _query(name, "SELECT table_name FROM information_schema.tables WHERE table_schema = %s")}
            assert "memory" in tables
            names = {_text(r[0]) for r in _query(name, "SELECT index_name FROM information_schema.statistics WHERE table_schema = %s AND table_name = 'document'")}
            assert any(n for n in names if n != "PRIMARY") and "idx_doc_kb_id" not in names
            cols = _query(name, "SELECT column_name FROM information_schema.statistics WHERE table_schema = %s AND table_name = 'document' AND index_name <> 'PRIMARY'")
            assert "kb_id" in {_text(c[0]) for c in cols}
        finally:
            database.close_all()
            DB.initialize(None)
